### ISSUE TITLE
LogHandler在Windows下面有非常严重的冲突问题

### ISSUE THREAD

**Issue by xujun05** [jhao104/proxy_pool#103]
大约运行1天后，均会出现log被占用，无法写入的问题。文件无法删除，必须重启机器才能解决。

**Comment by jhao104** [comment]
是的，貌似loging模块在windows上使用多进程写多一份日志文件会出问题。文件删不掉是因为有后台进程在占用。验证代理的时候使用了多进程

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
