### ISSUE TITLE
删除后的IP是否还会再获取到

### ISSUE THREAD

**Issue by geekjam** [jhao104/proxy_pool#108]
如题

**Comment by jhao104** [comment]
删除只是在可用代理的队列中删除，下次刷新还是可能会拿到。

这个得看你刷新的间隔和代理网站更新速度，一般每次抓前几页，更新的快的话不会有重复

**Comment by codejam1024** [comment]
我修改了你的验证代理的，改成抓取指定页面内容，如果返回我指定的内容则是有效。但是，验证增加进数据库了，下次获取到代理，使用的时候又不能用了的情况，你清楚是什么原因吗

**Comment by jhao104** [comment]
@codejam1024 代理时效性太低了吧

**Comment by jhao104** [comment]
@codejam1024  实践证明这样效果并不好。 本来有效代理时效性就极低，可能就验证当时有效。而有些自建的代理就很稳定，服务没挂就一直能用。 所以最好的就是使用前验证。 现在的机制的抓到的代理验证通过就留着，然后隔一段时间再去验证。 但是也有可能在中间时候代理失效。
总之，只要不是自建的代理，是不能保证有效性的。而且代理一次失效丢弃就行，需要反复验证的是未效的代理

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
