### ISSUE TITLE
关于IP定期更新的问题

### ISSUE THREAD

**Issue by StSphinx** [jhao104/proxy_pool#11]
在代理程序运行一段时间后，会出现大量僵尸进程， 如下：
<img width="774" alt="2017-01-11 1 04 05" src="https://cloud.githubusercontent.com/assets/7161664/21816135/f5d5ae2c-d799-11e6-964b-ad0ffa492d8f.png">

猜测是定期更新的ProxyRefreshSchedule类有bug~

**Comment by jhao104** [comment]
目前ProxyRefreshSchedule只是一个简单的代理验证，应该不会有问题。你试试把进程数量调低一点。间隔时间加长一点

**Comment by StSphinx** [comment]
我觉得是这个问题， 在ProxyRefreshSchedule.py文件中的main函数：
def main(process_num=100):
    p = ProxyRefreshSchedule()
    p.refresh()

    for num in range(process_num):
        P = Process(target=refreshPool, args=())
        P.start()
    print '{time}: refresh complete!'.format(time=time.ctime())

我猜测你是想启动100个进程去随机刷新raw_proxy_queue中的IP进行验证，然后这个main执行结束就退出了，所以这100个进程就变成僵尸进程了。

**Comment by jhao104** [comment]
你用的是ssdb吗？子进程refreshPool里面并不是个死循环呀，正常情况下：当代理全部验证完的时候raw_proxy为None，循环退出，子进程也会退出的。

**Comment by jhao104** [comment]
不过到还有有种可能，这个主进程是用BlockingScheduler起的。你将那段代码改为
def main(process_num=100):
    p = ProxyRefreshSchedule()
    p.refresh()
    for num in range(process_num):
        P = Process(target=refreshPool, args=())
        P.daemon = True
        P.start()
        P.join()
    print '{time}: refresh complete!'.format(time=time.ctime())
试试

**Comment by sksweet** [comment]
这个问题我也试了一下，把作者大大的修改:子进程改为守护进程后，确实没有哪么多python进程了，一直保持10来个左右吧.

**Comment by StSphinx** [comment]
@jhao104 

def main(process_num=100):
    p = ProxyRefreshSchedule()
    p.refresh()
    pl = []
    for num in range(process_num):
        P = Process(target=refreshPool, args=())
        P.daemon = True
        pl.append(P)

    for num in range(process_num):
        pl[num].start()

    for num in range(process_num):
        pl[num].join()
这样吧，否则都阻塞在join那了，还是一个进程吧
