### ISSUE TITLE
启动项目后127.0.0.1:5010/*均卡住无反应。

### ISSUE THREAD

**Issue by yangcongtougg** [jhao104/proxy_pool#110]
#### 按照步骤配置好之后，redis中无数据，localhost:5010无反应。
- 分别启动Run下的main.py文件或者依次到Api下启动ProxyApi.py,Schedule下启动ProxyRefreshSchedule.py和ProxyValidSchedule.py均无反应。
![qq 20180126180032](https://user-images.githubusercontent.com/16517304/35435073-554545ec-02c4-11e8-9c53-3ea3912a8372.png)
![qq 20180126180052](https://user-images.githubusercontent.com/16517304/35435078-5eaa5226-02c4-11e8-880e-838562474287.png)
![20180126180516](https://user-images.githubusercontent.com/16517304/35435086-6341a348-02c4-11e8-9150-6141fc0bfec3.png)
![qq 20180126180113](https://user-images.githubusercontent.com/16517304/35435103-6902fde0-02c4-11e8-905c-56a687222efd.png)
![qq 20180126180325](https://user-images.githubusercontent.com/16517304/35435107-6ba2c0e4-02c4-11e8-8d9b-d1eeaf337a32.png)
> 还有一点想请教，自己定制要爬取的代理网站的话，爬虫规则及网页标签的提取规则，入库等代码要写在哪个文件？
十分的感谢，小白一枚。

**Comment by jhao104** [comment]
@yangcongtougg 可能是db没配置正确连不上吧，报错了看看日志的error。自己定制代理，看文档的[扩展代理](https://github.com/jhao104/proxy_pool#%E6%89%A9%E5%B1%95%E4%BB%A3%E7%90%86)部分

**Comment by yangcongtougg** [comment]
@jhao104 关键是还无报错信息，db的配置除了图2，请问还有其他地方吗？谢谢

**Comment by jhao104** [comment]
你单独前台启动ProxyApi.py 然后访问 可以看到所有访问日志。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by angelfly2000** [comment]
程序能跑起来，好开心^o^
