### ISSUE TITLE
ip代理池的使用

### ISSUE THREAD

**Issue by alexanderhawl** [jhao104/proxy_pool#111]
楼主，请问下，获取ip后，隔段时间使用，是不是需要重新运行一下这个程序。重新运行程序会把之前存储的代理ip清空掉吗？

**Comment by alexanderhawl** [comment]
我在main.py运行过程中使用ctrl+c停止了程序运行。然后localhost:5010不能访问。不知道是不是因为flask没有启动。

**Comment by jhao104** [comment]
怎么使用，看文档。 程序停了当然不能用了，建议用nohup或者supervisor启动

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
