### ISSUE TITLE
windows下没有无法使用gunicorn，大家可以使用gevent

### ISSUE THREAD

**Issue by xiaodang** [jhao104/proxy_pool#112]
1 安装 gevent 
`pip install gevent`
2 修改ProxyApi.py文件,引用gevent
`from gevent.wsgi import WSGIServer`
3 修改启动方法
![image](https://user-images.githubusercontent.com/7018239/35490646-1d28320e-04dc-11e8-8e21-9b4a67cdc4f4.png)
4 用nssm做成启动服务，单独启动API

**Comment by jhao104** [comment]
@xiaodang nice work!

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by aimilin6688** [comment]
我用的是gevent 1.3.4 版本导入
```python
from gevent.pywsgi import WSGIServer
```
nssm 使用：https://blog.csdn.net/shjh369/article/details/58064548

**Comment by hhaoao** [comment]
@xiaodang @aimilin6688  你们是咋样打包的，指教一下，我用cx_freeze打包生成的exe启动后无限生成自身的exe，如图：
![default](https://user-images.githubusercontent.com/11269610/44299529-86c7e000-a32a-11e8-9235-ee469b4fa66d.png)
我是直接打包Run目录下的main.py,cx_freeze的打包脚本如下：
```python
import sys
from cx_Freeze import setup, Executable
sys.path.append('../')


build_exe_options = {'packages': ['asyncio', 'idna', 'pkg_resources'], 'excludes': ['tkinter']}

setup(  name = 'proxy_pool',
        version = '0.1',
        description = '免费代理池',
        options = {'build_exe': build_exe_options},
        executables = [Executable('proxy_main.py')])
```

**Comment by hhaoao** [comment]
@jhao104 老哥，那如何找出哪里出问题了呢？小白我经验实在是有限，看不出哪里出问题了，也不知道如何debug这种打包问题。想百度谷歌都想不出关键词来搜索。。。
