### ISSUE TITLE
由于目标计算机积极拒绝

### ISSUE THREAD

**Issue by liangzhenghua** [jhao104/proxy_pool#113]
运行main.py时，能抓取代理IP，会显示
INFO freeProxyFirst: fetch proxy 218.207.212.79:8306

但是程序停止在了【由于目标计算机积极拒绝，无法连接。】

请问这个问题怎么解决？

**Comment by jhao104** [comment]
检查你的数据库配置吧，应该是数据库没连上

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by zjhzing** [comment]
我也出现这个问题。配置里面有两个post 一个是6379 一个是8888，这个怎么弄呢！谢谢你
