### ISSUE TITLE
redis.exceptions.ResponseError: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by ghost** [jhao104/proxy_pool#114]
![image](https://user-images.githubusercontent.com/13448645/35572799-607446ee-0610-11e8-94c7-fd2b783ab19f.png)
我的redis设置的有密码应该如何配置。应该是redis已经链接到了，只是不知道哪里设置密码

**Comment by gengjf** [comment]
改代码

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
