### ISSUE TITLE
可能需要过滤下80端口的代理

### ISSUE THREAD

**Issue by BigFF** [jhao104/proxy_pool#116]
def verifyProxyFormat(proxy):
    """
    检查代理格式
    :param proxy:
    :return:
    """
    import re
    verify_regex = r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}"
    return True if re.findall(verify_regex, proxy) else False

re.findall(verify_regex, proxy) and proxy.split(':')[1] != 80 and 1 <=int(proxy.split(':')[1] <= 65535

这里改成这样？ 有些80端口的代理在校验的时候其实就是访问ip的http 返回值是正常的，但是不能作为代理存在

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by dengyinlei** [comment]
确实，80开头的端口好多都不能用
