### ISSUE TITLE
验证代理格式小改进

### ISSUE THREAD

**Issue by Dengqlbq** [jhao104/proxy_pool#117]
Util/utilFunction.py/verifyProxyFormat

def verifyProxyFormat(proxy):
    """
    检查代理格式
    :param proxy:
    :return:
    """
    import re
    verify_regex = r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}"

    # 在某些用户自己扩展的代理获取函数中可能在抓取代理时或抓取后处理时混入奇怪的东西
    # 例如 “1.2.3.4:56abc”
    # 当前判断方式仍会返回True
    # 建议：
    # 
    # ls = re.findall(verify_regex, proxy)
    # return True if len(ls) == 1 and ls[0] == proxy else False

    return True if re.findall(verify_regex, proxy) else False

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
