### ISSUE TITLE
目标计算机积极拒绝

### ISSUE THREAD

**Issue by zjhzing** [jhao104/proxy_pool#118]
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:8888. 由于目标计算机积极拒绝，无法连接

应该是我配置的问题，求教如何配置。配置文件里有两个post，一个6379，一个8888，这个怎么填

**Comment by jhao104** [comment]
@zjhzing 
```
# Config.ini 为项目配置文件
# 配置DB
type = SSDB       # 如果使用SSDB或redis数据库，均配置为SSDB
host = localhost  # db host
port = 8888       # db port
name = proxy      # 默认配置

# 配置 ProxyGetter
freeProxyFirst  = 1  # 这里是启动的抓取函数，可在ProxyGetter/getFreeProxy.py 扩展
freeProxySecond = 1
....

# 配置 HOST (api服务)
ip = 127.0.0.1       # 监听ip,0.0.0.0开启外网访问
port = 5010          # 监听端口
# 上面配置启动后，代理api地址为 http://127.0.0.1:5010
```
第一个port是你数据库的端口号, 第二个是api的端口号

**Comment by zjhzing** [comment]
在zip下载里面的config.ini中，我可以直接在那个文件里修改吗？里面有
type = SSDB
host = localhost
;port = 6379
port = 8888
name = proxy
这里的两个port分别是？

**Comment by zjhzing** [comment]
@jhao104

**Comment by zjhzing** [comment]
或者我可以新建一个。ini文件，将下面这段话复制上去呢（修改参数）
# Config.ini 为项目配置文件
# 配置DB
type = SSDB       # 如果使用SSDB或redis数据库，均配置为SSDB
host = localhost  # db host
port = 8888       # db port
name = proxy      # 默认配置

# 配置 ProxyGetter
freeProxyFirst  = 1  # 这里是启动的抓取函数，可在ProxyGetter/getFreeProxy.py 扩展
freeProxySecond = 1
....

# 配置 HOST (api服务)
ip = 127.0.0.1       # 监听ip,0.0.0.0开启外网访问
port = 5010          # 监听端口
# 上面配置启动后，代理api地址为 http://127.0.0.1:5010

**Comment by jhao104** [comment]
@zjhzing  默认的配置文件就是文档里面的啊 
https://github.com/jhao104/proxy_pool/blob/master/Config.ini

**Comment by zjhzing** [comment]
@jhao104 十分感谢你！我现在是用redis 。照我的理解，是不是只需要把port8888改为6379，其他都保持原状，比如type = SSDB    配置 HOST (api服务)都是不动就好呢

**Comment by zjhzing** [comment]
@jhao104 现在我的提示是configparser.MissingSectionHeaderError: File contains no section headers.应该就是配置文件没配好的问题

**Comment by jhao104** [comment]
@zjhzing 对的 你用我上面那个连接的配置文件 改一改就行了

**Comment by jhao104** [comment]
@zjhzing 对的 redis的话只改DB的端口就行

**Comment by zjhzing** [comment]
@jhao104  对的呢，我就是这么操作的。把port=8888改成6379
可最后还是这个问题

**Comment by jhao104** [comment]
@zjhzing  上面报错是说你配置文件问题 没有Section名字 就是那个大括号

**Comment by zjhzing** [comment]
[DB]
;Configure the database information
;type: SSDB/REDIS/MONGODB if use redis, only modify the host port，the type should be SSDB
type = SSDB
host = localhost
;port = 6379
port = 6379
name = proxy

[ProxyGetter]
;register the proxy getter function
freeProxyFirst  = 1
freeProxySecond = 1
freeProxyThird  =  
freeProxyFourth = 1
freeProxyFifth  = 1
freeProxySixth = 1
freeProxySeventh = 1

[HOST]
; API接口配置 http://127.0.0.1:5051
ip = 0.0.0.0
port = 5010
@jhao104    大括号是哪个呢

**Comment by zjhzing** [comment]
@jhao104 您好，是最上面那个[DB]吗？

**Comment by jhao104** [comment]
@zjhzing  https://www.cnblogs.com/DjangoBlog/p/3585945.html

**Comment by hujieuse** [comment]
为什么无法访问5010端口啊
