### ISSUE TITLE
SSDB和Redis配置问题

### ISSUE THREAD

**Issue by MiderWong** [jhao104/proxy_pool#121]
#### 3、看了下源码，都没有对设置了DB访问密码的支持，需要修复一下？

**Comment by jhao104** [comment]
不使用SSDB的话不需要安装它；
使用Redis和SSDB配种中的type都是SSDB 它俩数据结构和协议差不多的；
现在配置暂时是不支持密码的， 你可以在代码里面改 https://github.com/jhao104/proxy_pool/blob/275288d07416eed9de102e18d7aa42de31838eb0/DB/SsdbClient.py#L44

**Comment by MiderWong** [comment]
ok

**Comment by MiderWong** [comment]
需要更改的内容有点多啊
#### 1、修改`/Config.ini`文件
添加`password`项的设置：
```
[DB]
password = 
```
#### 2、修改`/Util/GetConfig.py`文件
添加获得`password`值的方法：
```
@LazyProperty
def db_password(self):
    return self.config_file.get('DB', 'password')
```
#### 3、修改`/DB/DbClient.py`文件
修改`76`行内容：
```
self.client = getattr(__import__(__type), __type)(name=self.config.db_name,
                                                          host=self.config.db_host,
                                                          port=self.config.db_port,
                                                          password=self.config.db_password)
```
#### 4、修改`/DB/SsdbClient.py`文件
修改`__init__`方法：
```
    def __init__(self, name, host, port, password):
        """
        init
        :param name: hash name
        :param host: ssdb host
        :param port: ssdb port
        :param password: ssdb password
        :return:
        """
        self.name = name
        self.__conn = Redis(connection_pool=BlockingConnectionPool(host=host, port=port, password=password))
```
总的步骤就是：
- 配置文件中添加password设置
- 在获取配置方法中添加对password的获取
- 在实例化DB时添加对password的支持

**Comment by jhao104** [comment]
@MiderWong  可以把你改好的代码提过来 我也懒的在写了 :smile:

**Comment by MiderWong** [comment]
本来是想提PR来着，但是SSDB没有验证，我用的是Redis，担心别人一更新就出错，所以就没提，等我搞了MongoDB和SSDB的password验证了，就提PR @jhao104 方便来个联系方式不，有问题请教

**Comment by pblh123** [comment]
是不是需要自己先安装redis，才能使用

**Comment by JoysKang** [comment]
是的，你需要有自己redis服务

**Comment by pblh123** [comment]
请问大神能更新一个redis的安装配置教程不，小白没用过。不会弄，谢谢

**Comment by pblh123** [comment]
谢谢，我去试试。我还不会用SSDB和Redis

**Comment by uhe1231** [comment]
发现个问题.
proxy_pool/DB/DbClient.py:79
添加了参数 `password`
但是, `proxy_pool/DB/RedisClient.py:25` 和 `proxy_pool/DB/MongodbClient.py:20` 没有使用
启动直接报错了.

**Comment by MiderWong** [comment]
什么错误？

**Comment by uhe1231** [comment]
我代码位置指出来了, 
就是在`DbClient`类里面传入了password的参数,
但是在`RedisClient`类的初始化函数, 和`MongodbClient`初始化函数里面没有接受!
