### ISSUE TITLE
虚拟机报错 proxies.copy 

### ISSUE THREAD

**Issue by Roron0a** [jhao104/proxy_pool#123]
```
 new_proxies = proxies.copy() if proxies is not None else {}
AttributeError: 'str' object has no attribute 'copy'
```

我用的方法

```
res = requests.get(url,proxies = p)
```

只能运行第一次爬去的数据

如果运行第二次 就会抱着个错误 不知道咋回事？

然而在本机上跑是没事 醉了。。

**Comment by jhao104** [comment]
` new_proxies = proxies.copy() if proxies is not None else {}` 你这段代码并不是项目里面的吧

**Comment by Roron0a** [comment]
是requests这个库里面的 很好奇为啥本机跑没事 虚拟机就会包这个错误？ 按理说都一样的库啊

**Comment by jhao104** [comment]
@Roron0a 看下是不是两个requests版本不一致

**Comment by Roron0a** [comment]
删除旧版本的request可以了 原来是使用错了 
谢谢作者 你有没有放个二维码啥的 我要请你喝咖啡
