### ISSUE TITLE
偶尔出现的日志错误信息

### ISSUE THREAD

**Issue by forvendettaw** [jhao104/proxy_pool#124]
![logerror](https://user-images.githubusercontent.com/24313853/38188246-b37bc2c4-368d-11e8-9340-79cdb6671d80.png)

**Comment by jhao104** [comment]
@forvendettaw 你这是在win上面吧 win上面日志多进程时日志有些问题 计划修复中

**Comment by forvendettaw** [comment]
昨天测试发现\proxy_pool\ProxyGetter\getFreeProxy.py下面的有些获取代理的方法由于代理网站变更已经失效了，我修改了一份，可以commit吗

**Comment by jhao104** [comment]
@forvendettaw 确实这个需要一直维护的, 你测试没问题可以提上来
