### ISSUE TITLE
请问大神如何部署服务呢

### ISSUE THREAD

**Issue by forvendettaw** [jhao104/proxy_pool#129]
想使用 nginx + gunicorn + supervisor + flask部署这个服务，但是服务总入口在main中，不知道该怎么弄，求大神指导

**Comment by forvendettaw** [comment]
已经部署好了，感谢

**Comment by jhao104** [comment]
@forvendettaw 嗯 看文档的启动部分, api是单独的。你用gunicorn拉起ProxyApi.py就行
