### ISSUE TITLE
windows下使用api经常卡死

### ISSUE THREAD

**Issue by lycomputer** [jhao104/proxy_pool#130]
我在windows下使用，从2008换到2012，都出现proxyapi运行一段时间卡死的情况，请问应该如何处理才能保证长时间稳定运行呢？

**Comment by lycomputer** [comment]
https://github.com/jhao104/proxy_pool/issues/112
使用了这位大神的方法，使用了几个小时，目前API已经不会阻塞了，具体能不能长时间稳定运行，还有待测试，感谢作者，感谢热心的大神们。

**Comment by lycomputer** [comment]
经过24小时以上的测试，再也没有发生api接口阻塞的情况了，就是日志会报错，但是没有影响使用，感谢！

**Comment by hhaoao** [comment]
这里的卡死对于我等小白来说描述的太笼统了，结果翻遍了issues,才发现这里说的卡死、阻塞才是我遇到的情况。特地在此做下记录，让更多的小白知道。
   我的系统是windows10，遇到的卡死、阻塞情况是这样的，api获取不到proxy地址，如果没设置超时的话，你肯定有体会，用浏览器登录127.0.0.1:5010，浏览器一直打圈，无法显示界面。
