### ISSUE TITLE
self.db.put感觉有点问题呢，每次都会自动加1呢

### ISSUE THREAD

**Issue by highroom** [jhao104/proxy_pool#132]
self.db.put感觉有点问题呢，看了下是调用self.__conn.hincrby，返回的时候会对num值自动加1呢，如果代理值是1，验证不过调用put(proxy, num+1)后，代理的num就变成3了，而且就算验证通过num值也不会变，num=1的，put(proxy, num-1)后，代理的num还是1

**Comment by jhao104** [comment]
@halleywj  是的 之前那个有问题 改成hset了

**Comment by highroom** [comment]
@jhao104 RedisClient.py里的PUT没有改到呢，还是用的hincrby

**Comment by jhao104** [comment]
@highroom RedisClient.py已经没有了 ssdb和redis都是用SsdbClient.py
