### ISSUE TITLE
似乎不能自动fetch proxy？

### ISSUE THREAD

**Issue by LuXiaoYuan666** [jhao104/proxy_pool#133]
在win10系统cmd命令行下面，可以进行proxycheck
但是不能自动fetch proxy，非常奇怪。
看了源代码，默认是10分钟会自动抓取更新代理，但好像没什么作用啊。

除非，人工在cmd下按回车，就可以进行proxycheck了。。

**Comment by jhao104** [comment]
@Muse1993 我这边机器上刚跑了没这个问题呢?  定时抓取是使用APschedule模块,在win10上没有你这种问题过

**Comment by Muse1993** [comment]
@jhao104 看到报了一个warning 
WARNING:apscheduler.scheduler:Execution of job "main (trigger: interval[0:00:08], next run at: 2018-04-15 22:48:15 CST)" skipped: maximum number of running instances reached (1)
fetch proxy我设定是8秒一抓 估计是太快了。。 但是代理失效太快（我用的付费代理 每5秒最多抓10个）我没办法 然后其实next run也一直没用起效果 就再也不能run了 
怎么样才能规避这个问题 proxycheck跳过有用吗

**Comment by jhao104** [comment]
对 确实是你一次任务的执行时间超过了间隔时间。 抓的时候不检查也行呀 
https://github.com/jhao104/proxy_pool/blob/c44f3e8150d6c8b38e3baa150cad82b5b2bc8112/Schedule/ProxyRefreshSchedule.py#L59

你把这里的 `validUsefulProxy(raw_proxy)` 改成 `True` 就行了
