### ISSUE TITLE
这些代理能隐藏真实IP吗？

### ISSUE THREAD

**Issue by Sabirjan** [jhao104/proxy_pool#134]
这些代理能隐藏真实IP吗？
透明代理还是匿名代理？

**Comment by Sabirjan** [comment]
好的，谢谢！还有一个问题，怎么实现国内和国外的IP？这个需求调研第三方的IP地区判断接口吗？

**Comment by jhao104** [comment]
@Sabirjan 国外ip和国内ip是根据你抓取部分定的呀 你抓的国外的就是国外的。

现在接口没有根据国内外筛选

要么就是部署两套 国外一套国内一套
