### ISSUE TITLE
针对每条不同的HTTP请求更换一次代理IP

### ISSUE THREAD

**Issue by Just2co** [jhao104/proxy_pool#135]
@jhao104  老大好，能否增加一个功能，就是针对http爬取请求，每条或者某几条走某个代理IP，而不是固定的那一个，毕竟代理IP池里面那么多可用IP，只用那么一个有点浪费啊，而且对于用爬虫刷点击率来说，每个http请求都换一次IP，这样就能把点击刷起来，你觉得呢？

**Comment by jhao104** [comment]
@Just2co 怎么用代理完全是你爬虫代码部分自己控制啊  代理池只是提供代理获取接口
/get 接口每次随机拿一个代理 /delete 是删除  你拿出来用几次完全是在爬虫部门控制的吧

**Comment by Just2co** [comment]
@jhao104  哈哈，我觉得你那边写了，我就不用改动我的代码啦！因为我刚学会， 还不会自己定制呢，对了，这个支持MongoDB数据库吗？服务器上已经装了那个，不想重复安装SSDB这种非关系数据库

**Comment by jhao104** [comment]
@Just2co 有支持，只是很久没更新驱动了 不知道现在有没有问题， 最好使用redis或者ssdb

爬虫使用的代理的话应该是 从/get 接口获取一个代理出来，然后一直用 直到代理失效或者被ban掉 再重新 /get一个新代理。 因为代理的时效性本来就低  。 Python代码很简单的， 我也不知道你爬虫怎么使用的 没法给你写

**Comment by Just2co** [comment]
@jhao104  就下面这部小说 http://www.17k.com/list/2785153.html  我已经爬取了这部小说的所有章节URL，现在要做到爬虫自动打开每一章节的时候，代理IP就更换一下，这样人气点击就刷上来了，不然用一个IP去爬上万次的，在只给你算一次点击。这个代码要咋写呢？给个提示即可

**Comment by Just2co** [comment]
@jhao104 你写的连接MongoDB支持里面，怎么没看到你填数据库的账号跟密码进去？ 数据库的名字是db2吗？

**Comment by jhao104** [comment]
@Just2co Mongdb的client的配置不支持用户名密码方式登录，只能去改代码，

https://github.com/jhao104/proxy_pool/blob/ac8842504f488d6139e10370ecbbf3806be399e8/DB/MongodbClient.py#L19-L23

```
uri = "mongodb://%s:%s@%s:%s" % (
                user, password, host, port)
self.client = MongoClient(uri)
```

**Comment by Just2co** [comment]
@jhao104 另外一个朋友也是这样跟我讲的，太感谢了，对了，他说MongoDB里面如果没有数据库的话，会自动建一个，self.db = self.client.proxy    后面这个proxy应该就是数据库的名字,如果脸上MongoDB client找不到这个库，就会自动新建，   self.name = name  这行代码是做什么的？放那里不改动行不行？

**Comment by Just2co** [comment]
@jhao104 我已经把相关连接MongoDB的代码都写好了，待会有时间我弄到服务器上去，跑起来，看看是否出问题，MongoDB数据库可视化管理工具是robo 3T，我这边都装好了，应该会自动生成数据库及里面的表的。我去年12月份把整个项目装好到笔记本的ubuntu里面过，所以对这次还是有信心的， 只不过不想重复安装数据库而已！但愿成功！

**Comment by Just2co** [comment]
@jhao104  pip安装lxml 3.7.1这个包的时候，报错：
`Error:  An error occurred while installing lxml==3.7.1!
  Failed building wheel for lxml`

**Comment by jhao104** [comment]
@Just2co 装包的问题你自己百度吧 直接用pip就可以

**Comment by Just2co** [comment]
@jhao104 原来是centOS 必须安装 libxml2 和 libxml2-del 这两个包，哎！

**Comment by Just2co** [comment]
@jhao104  搞定，从昨天下午折腾到现在，终于成功！今天大半天都是卡在centos 安装lxml3.7.1这里，各种问题，久拖不决，最后直接就是pip install lxml 一行命令搞定，啥错误都没出现。MongoDB数据库找你那样改，一次性成功，robo 3T连接数据库服务器刷新之后，出现了proxy这个库

**Comment by Just2co** [comment]
@jhao104  我还想请教一下，return到数据库的ip跟端口是经过检测后的可用代理，还是直接lxml解析API获取到的代理啊？另外，万一爬到重复的ip跟端口，扔到数据库里之后，是怎么处理的？数据库自动会进行处理吧？比如查重操作

**Comment by jhao104** [comment]
@Just2co 数据库里面代理分useful_proxy和raw_proxy。 每次定时检测和抓取入库的时候会排重  代理有效性检测只做了http的 至于其他方式你可以自己去扩展
https://github.com/jhao104/proxy_pool/blob/ac8842504f488d6139e10370ecbbf3806be399e8/Util/utilFunction.py#L91-L108

**Comment by Just2co** [comment]
@jhao104 刚从useful_proxy里随便找了一个，居然是美国IP，国外可用IP在这里 的比例应该不太大吧？太大就会出问题的，刷人气，那些小说大部分都是国内用户跑去看的

**Comment by jhao104** [comment]
@Just2co 在Config.ini里配置那些网站抓那些网站不抓
https://github.com/jhao104/proxy_pool/blob/master/ProxyGetter/getFreeProxy.py

**Comment by Just2co** [comment]
@jhao104  老大，总感觉这段代码有点问题，逻辑多加了一层就卡壳了，帮我改一改，谢谢！
`for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
        retry_count = 2
        while retry_count > 0:
    try:
        html = requests.get(chapterurl, headers = head, proxies={"http": "http://{}".format(proxy)})  # 用代理抓取页面
        # 使用代理访问
        return html
    except Exception as e:
        retry_count -= 1
    # 出错2次, 删除代理池中代理
        delete_proxy(proxy)
        return None`

**Comment by Just2co** [comment]
> 
for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
        retry_count = 2
        while retry_count > 0:
    try:
        html = requests.get(chapterurl, headers = head, proxies={"http": "http://{}".format(proxy)})  # 用代理抓取页面
        # 使用代理访问
        return html
    except Exception as e:
        retry_count -= 1
    # 出错2次, 删除代理池中代理
        delete_proxy(proxy)
        return None
>

**Comment by Just2co** [comment]
_for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
        retry_count = 2
        while retry_count > 0:
    try:
        html = requests.get(chapterurl, headers = head, proxies={"http": "http://{}".format(proxy)})  # 用代理抓取页面
        # 使用代理访问
        return html
    except Exception as e:
        retry_count -= 1
    # 出错2次, 删除代理池中代理
        delete_proxy(proxy)
        return None_

**Comment by Just2co** [comment]
下面加多了一层判断逻辑，我就不知道怎么写了，能帮我改一下吗？谢谢了
`for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
        retry_count = 2
        while retry_count > 0:
    try:
        html = requests.get(chapterurl, headers = head, proxies={"http": "http://{}".format(proxy)})  # 用代理抓取页面
        # 使用代理访问
        return html
    except Exception as e:
        retry_count -= 1
    # 出错2次, 删除代理池中代理
        delete_proxy(proxy)
        return None`

**Comment by Just2co** [comment]
太感谢了，我用的是它自带的单引号，所以乱了，现在再帮我瞅瞅，你那种脚本引用某几行，代码前面还显示行号，还显示脚本名称是怎么实现的？？

**Comment by jhao104** [comment]
```
for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
    retry_count = 2
    while True:
        try:
            html = requests.get(chapterurl, headers = head, proxies={"http": "http://{}".format(proxy)})  # 用代理抓取页面
            # 使用代理访问
            print("craw success: %s" % chapterurl)
            break
        except Exception as e:
            retry_count -= 1
            if retry_count < 0:
            # 出错2次, 删除代理池中代理
                delete_proxy(proxy)
                print("craw error: %s" % chapterurl)
                break
```

**Comment by Just2co** [comment]
@jhao104 看懂了，我想给try: 下面那个代码段来个计数，刷到212页，整个脚本刷点击任务完成，怎么写？下面这样写行不行？
```
for index, chapterurl in enumerate(urls):
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
        if index > 212:
    break
    retry_count = 2
```

**Comment by Just2co** [comment]
@jhao104 写的好像又问题，只打印出来问题的章节URL
```
fsf@localhost spiders]$ python renqi.py
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK5Pj.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK6Ow.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK6Oj.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK6PT.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK6QD.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK7OT.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK7PD.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK7Qw.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK8OD.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK8Pw.html
craw error: http://www.jingyu.com/chapter/7aCkERa7MHK8Pj.html
```

**Comment by Just2co** [comment]
@jhao104 问题貌似出在这里，index 计数函数默认从0开始的，所以从for循环的第一个url开始，proxy都是空值没有ip
```
    if (index + 1) % 3 == 0:
        proxy = get_proxy()  # 每两次随机一次代理
```

**Comment by Just2co** [comment]
@jhao104 已经定位到问题原因了，把那些循环判断全部关掉,proxy = 18.197.1x8.1x5:3128这种固定的代理爬页面，一切正常，但是把proxy=get_proxy 自动化一弄，就没有一个成功的，全部都是有问题，尽管每次重启脚本get到的代理IP都在变，提示如下，都是代理不可用：
```
   raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: b'18.197.1x8.1x5:3128'
```

**Comment by splinter21** [comment]
楼主你直接get_all在本地取不就行了
