### ISSUE TITLE
windows报错 

### ISSUE THREAD

**Issue by puti-flower** [jhao104/proxy_pool#137]
WARNING:apscheduler.scheduler:Execution of job "main (trigger: interval[0:10:00]
, next run at: 2018-04-18 00:09:06 CST)" skipped: maximum number of running inst
ances reached (1)

**Comment by jhao104** [comment]
@amongtheflowers ProxyRefreshSchedule的间隔时间不能大于执行一次的时间

**Comment by Just2co** [comment]
@jhao104    发现requests.get("http://123.207.35.36:5010/get/").content方式取得的ip格式不正常，这种方式取到的是二进制形式的，而后面requests.get里面的参数需要字符串形式的，正确的代理IP形式应该是"http://45.113.71.123:8080"  ，应该弄成text文本字符串形式
```
proxy = requests.get("http://123.207.35.36:5010/get/").content
proxy
b'45.113.71.123:8080'
p = "http://{}".format(proxy)
p
"http://b'45.113.71.123:8080'"
```

**Comment by Just2co** [comment]
@jhao104 OK，困扰了我昨天大半天的问题终于搞定了，已经输出正常结果了
```def get_proxy():
    return requests.get("http://127.0.0.1:5010/get/").text```
