### ISSUE TITLE
python2.6在安装ssdb python驱动是报错

### ISSUE THREAD

**Issue by Sengege** [jhao104/proxy_pool#15]
Collecting ssdb
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached ssdb-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-sfGK5r/ssdb/setup.py", line 5, in <module>
        from ssdb import __version__
      File "ssdb/__init__.py", line 2, in <module>
        from ssdb.client import StrictSSDB, SSDB
      File "ssdb/client.py", line 74
        return {k:int(v) for k,v in list_to_dict(lst).items()}
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sfGK5r/ssdb

**Comment by jhao104** [comment]
试试·在这里下载源码安装https://github.com/wrongwaycn/ssdb-py

**Comment by vicre** [comment]
@Sengege  https://github.com/wrongwaycn/ssdb-py/issues/5
是因为里面有段代码 return {k:int(v) for k,v in list_to_dict(lst).items()} 这个要2.7才支持，
2.6 可以这样return dict([k,int(v)] for k,v in list_to_dict(lst).items())
--> 可以下载源码 自己安装
git clone https://github.com/wrongwaycn/ssdb-py.git  
cd ssdb-py
sudo python setup.py install

**Comment by wolther47** [comment]
建议将 ssdb 的依赖更换成其他的 Fork，原作者已经停止维护

**Comment by jhao104** [comment]
现在项目已不使用ssdb的python驱动，因为ssdb兼容redis协议，所以直接使用redis.py操作ssdb
