### ISSUE TITLE
建议可在config.ini增加一个翻墙代理IP设置

### ISSUE THREAD

**Issue by highroom** [jhao104/proxy_pool#150]
建议可在config.ini增加一个翻墙代理IP设置，在getproxyfee.py的freeProxyWall*增加使用代理访问，这样在抓取需要翻墙的网站时，可以读取对应的代理来访问

**Comment by huadaonan** [comment]
找封呢啊。自己加

**Comment by jhao104** [comment]
墙外网站自己加吧
