### ISSUE TITLE
SSDB's default port is not equal to Config.ini when using docker.

### ISSUE THREAD

**Issue by luozhenyu** [jhao104/proxy_pool#155]
Default port in Config.ini is 6379.

> [DB]
;Configure the database information
;type: SSDB/REDIS/MONGODB if use redis, only modify the host port，the type should be SSDB
type = SSDB
host = 127.0.0.1
port = 6379
;port = 8888
name = proxy

However, default port of [ssdb.conf](https://github.com/ideawu/ssdb/blob/6a97e82fc93aecb7ea7969bec3ad2235962c7fbb/ssdb.conf#L10) is 8888
> server:
	ip: 127.0.0.1
	port: 8888

So there is a problem when using docker with default setting.

I suggest to inserting a line in Dockerfile. `-e 's@port:.*@port: 6379@' \`

**Comment by JoysKang** [comment]
是的，赞成使用同一端口，这已经给我造成疑惑了

**Comment by JoysKang** [comment]
;type: SSDB/REDIS/MONGODB if use redis, only modify the host port，the type should be SSDB
这是config.ini的描述


```python
    def __initDbClient(self):
        """
        init DB Client
        :return:
        """
        __type = None
        if "SSDB" == self.config.db_type:
            __type = "SsdbClient"
        elif "REDIS" == self.config.db_type:
            __type = "RedisClient"
        elif "MONGODB" == self.config.db_type:
            __type = "MongodbClient"
        else:
            pass
```
上边是__initDbClient 的代码， 两者矛盾
