### ISSUE TITLE
目前代理没有区分http和https，这块能做一下吗

### ISSUE THREAD

**Issue by xrfinbupt** [jhao104/proxy_pool#156]
🙏

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L102

把这个改成 `http://httpbin.org/ip` 就可以验证https代理

**Comment by JoffreyN** [comment]
@jhao104 能写个api吗，比如访问get_https就返回https的代理

**Comment by ludanxer** [comment]
@jhao104 
如果想要验证https的代理，只将 [proxy_pool/Util/utilFunction/Line 102](https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L102) 中的`http://httpbin.org/ip`修改为`https://httpbin.org/ip`似乎是不够的。


还需要将 [proxy_pool/Util/utilFunction/Line 99](https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L99) 中的`proxies = {"http": "http://{proxy}"}`修改为`proxies = {"https": "https://{proxy}"}` 或 `proxies = {"https": "http://{proxy}"}`


如果在使用Shadowsocks代理，可以做以下尝试：
```
import requests
proxies = {'http' : 'http://127.0.0.1:1087'} # depend on your setting
r = requests.get('https://httpbin.org/ip', proxies=proxies)
print(r.text)
```
以上输出了我本机的ip地址

而以下代码则成功输出了代理的ip地址:
```
import requests
proxies = {'https' : 'http://127.0.0.1:1087'} # depend on your setting
r = requests.get('https://httpbin.org/ip', proxies=proxies)
print(r.text)
```

**Comment by ludanxer** [comment]
如果希望验证https代理，只将 [proxy_pool/Util/utilFunction.py/Line 102](
https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L102) 中的`http://httpbin.org/ip` 修改为 `https://httpbin.org/ip` 似乎是不够的。只做以上修改会使用本机的ip发送请求。

还需要将 [proxy_pool/Util/utilFunction.py/Line 99](https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L99) 中的 `proxies = {"http": "http://{proxy}"` 修改为 `proxies = {"https": "http://{proxy}"` 或 `proxies = {"https": "https://{proxy}"`

如果使用ss代理可以进行以下尝试：
```
import requests
proxies = {'http' : 'http://127.0.0.1:1087'} # depend on your setting
r = requests.get('https://httpbin.org/ip', proxies=proxies)
print(r.text)
```
以上代码返回了我本机的ip地址

而下面的代码正确的返回了代理的ip地址
```
import requests
proxies = {'https' : 'http://127.0.0.1:1087'} # depend on your setting
r = requests.get('https://httpbin.org/ip', proxies=proxies)
print(r.text)
```

**Comment by vindsora** [comment]
确实如此，以前没注意到这个问题，代理消耗很大，经常报错```Max retries exceeded with url...``` 

暂时解决方案是 在 checkproxy 和项目使用中 均请求了两次（http和https） 

如果可以在存ssdb的时候就区分清楚，再修改一下接口就完美了

**Comment by jhao104** [comment]
> 确实如此，以前没注意到这个问题，代理消耗很大，经常报错`Max retries exceeded with url...`
> 
> 暂时解决方案是 在 checkproxy 和项目使用中 均请求了两次（http和https）
> 
> 如果可以在存ssdb的时候就区分清楚，再修改一下接口就完美了

后面会加，加区别http和https肯定要请求两次
