### ISSUE TITLE
现在很多代理貌似无法隐藏真实IP

### ISSUE THREAD

**Issue by raymondmars** [jhao104/proxy_pool#161]
很多代理发起请求的时候，貌似添加上了 HTTP_X_FORWARDED_FOR ，使得，貌似每次目标网站都能获取客户机的真实 IP。有遇到这种情况的吗？

**Comment by jhao104** [comment]
@RobotJiang 代理也分匿名和透明，透明代理对方服务器就能获取你真实IP

**Comment by JimCurryWang** [comment]
@jhao104  為何有時候使用的是匿名代理 還是一樣透露真實IP 呢？ 是代理網站寫的匿名代理是假的？

**Comment by JimCurryWang** [comment]
@jhao104  我用類似下方這種網站測試的
https://www.iplocation.net/find-ip-address

**Comment by jhao104** [comment]
@JimCurryWang 你可以把这里的验证改成你那测试网站的返回高匿才返回True
https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L91-L108

**Comment by likenji** [comment]
`def validUsefulProxy(proxy):
    """
    检验代理是否可用
    :param proxy:
    :return:
    """
    if isinstance(proxy, bytes):
        proxy = proxy.decode('utf8')
    proxies = {"http": "http://{proxy}".format(proxy=proxy)}
    try:
        # 超过10秒的代理就不要了
        r = requests.get('http://httpbin.org/ip', proxies=proxies, timeout=10, verify=False)
        if r.status_code == 200:
            # logger.info('%s is ok' % proxy)
            if eval(r.content.decode("utf8"))["origin"] == proxy.split(":")[0]:
                #只要高匿IP
                return True
            else:
                return False
    except Exception as e:
        # logger.error(str(e))
        return False`
给出了一个只要高匿IP的实现。

**Comment by likenji** [comment]
> `def validUsefulProxy(proxy): """ 检验代理是否可用 :param proxy: :return: """ if isinstance(proxy, bytes): proxy = proxy.decode('utf8') proxies = {"http": "http://{proxy}".format(proxy=proxy)} try: # 超过10秒的代理就不要了 r = requests.get('http://httpbin.org/ip', proxies=proxies, timeout=10, verify=False) if r.status_code == 200: # logger.info('%s is ok' % proxy) if eval(r.content.decode("utf8"))["origin"] == proxy.split(":")[0]: #只要高匿IP return True else: return False except Exception as e: # logger.error(str(e)) return False`
> 
> 给出了一个只要高匿IP的实现。
为什么排版这么烂...

**Comment by qm8956** [comment]
我用您提供的代码获取的高匿IP,我在[http://web.chacuo.net/netproxycheck](url)这个网站上测试代理，获得的都是透明代理，并没有测出来那个是高匿IP，我爬去boss直聘被封禁之后，就再也发不出一个正常可用的代理，并且我本地IP也被封禁

**Comment by likenji** [comment]
邮件已到账。我会尽快回复的

**Comment by DoiiarX** [comment]
这么多年了，似乎都没有解决。离奇。

**Comment by likenji** [comment]
邮件已到账。我会尽快回复的
