### ISSUE TITLE
redis数据库有数据但是我的api一直掉不到数据

### ISSUE THREAD

**Issue by FlyingPigHasDream** [jhao104/proxy_pool#163]

**Comment by jhao104** [comment]
@FlyingPigHasDream 数据库存了两种 一种raw_proxy 这是原始抓取的代理 
另一种是useful_proxy 才是验证通过的代理。

**Comment by FlyingPigHasDream** [comment]
l另外一个存的操作在哪里

**Comment by jhao104** [comment]
@FlyingPigHasDream 你按照文档配置启动的话 自己就会去抓取验证储存的 
或者你可以分别启动那三个进程  文档你又说

**Comment by seaninrc** [comment]
@jhao104  我按顺序跑了四个文件数据库里还是只有raw_proxy，没有useful_proxy 可能是什么原因啊

**Comment by jhao104** [comment]
@seaninrc 要么运行main 要么运行其他三个 
usefule没有数据看下 ProxyValidSchedule 运行的日志 有没有运行通过的

**Comment by seaninrc** [comment]
@jhao104 我按顺序跑其他三个就生成了两个日至，好像没有ProxyValidSchedule的

**Comment by seaninrc** [comment]
@jhao104 那个proxy_manager就是它生成的日至吧，显示INFO Valid Complete通过了呀

**Comment by seaninrc** [comment]
@jhao104 
    def putQueue(self):
        self.db.changeTable(self.useful_proxy_queue)
        self.proxy_item = self.db.getAll()
        print(len(self.proxy_item))
        for item in self.proxy_item:
            self.queue.put(item)
用的redis数据库里面有数据，但是这个getall()不知道为什么没拿到值

**Comment by wzdata** [comment]
@jhao104  请问多等几分钟什么意思，我遇到了跟你一样的问题，raw_proxy上千个，userful_proxy一直是0个，两种运行方法都跑了

**Comment by wzdata** [comment]
@seaninrc  请问多等几分钟什么意思，我遇到了跟你一样的问题，raw_proxy上千个，userful_proxy一直是0个，两种运行方法都跑了
