### ISSUE TITLE
按照教程运行安装后，IP没有存储到数据库中SSDB

### ISSUE THREAD

**Issue by pblh123** [jhao104/proxy_pool#165]
问题：
1、按照github教程安装后，ip没有存储到数据库中.（SSDB查询反馈）
ssdb 127.0.0.1:8888> dbsize
0
(0.000 sec)

2、网页访问一直拒绝
使用的是wind7的虚拟机上Ubuntu 18跑代理，wind7上访问拒绝

**Comment by jhao104** [comment]
@pblh123 你没有启动成功吧？正常raw_proxy应该是必须有的
