### ISSUE TITLE
能否设置代理池只获取高匿IP

### ISSUE THREAD

**Issue by hello-cyb** [jhao104/proxy_pool#169]
@jhao104 您好,之前我在一个issues下看到您说准备设置可以只获取高匿IP,可是我在文档里并没有看到有相应的设置,当然我可以自己扩展代理然后过滤掉透明代理,提这个issues是防止我漏看了,同时确认一下抓取下来的免费代理在存入nosql数据库之前的存活验证是否是程序自动执行?

**Comment by jhao104** [comment]
可以自己扩展 
https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L91-L108

这里验证只是验证了status_code等于200 
[http://httpbin.org/ip](http://httpbin.org/ip)这个接口会返回请求的ip信息。
返回有三种 本机ip  本机ip+代理ip  代理ip

判断返回的ip和你的代理ip一致才返回True 就ok

**Comment by hello-cyb** [comment]
感谢回复 已了解

**Comment by wqh0109663** [comment]
太酷了 起飞

**Comment by Alexhaoge** [comment]
> 可以自己扩展
> https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L91-L108
> 
> 这里验证只是验证了status_code等于200
> http://httpbin.org/ip这个接口会返回请求的ip信息。
> 返回有三种 本机ip 本机ip+代理ip 代理ip
> 
> 判断返回的ip和你的代理ip一致才返回True 就ok

现在这里的文件名和代码修改了，新增了一个自定义校验函数，可以把高匿的判断直接写在这里
https://github.com/jhao104/proxy_pool/blob/068485feb00564036e0e15dbd5076498d241f5c4/util/validators.py#L51-L58

我是这么写的
```Python
@validator
def customValidator(proxy):
    proxies = {"http": "http://{proxy}".format(proxy=proxy), "https": "https://{proxy}".format(proxy=proxy)}
    try:
        r = requests.get('http://httpbin.org/ip', proxies=proxies, timeout=10, verify=False)
        if r.status_code == 200 and r.json()['origin'] in proxy:
            return True
    except Exception as e:
        pass
    return False

```
