### ISSUE TITLE
redis数据库有raw_proxy表和数据，但调用api显示no proxy!

### ISSUE THREAD

**Issue by hhpss** [jhao104/proxy_pool#171]
![Uploading image.png…]()

**Comment by PurcellH** [comment]
![image](https://user-images.githubusercontent.com/38977042/44624987-e6784980-a92f-11e8-98bc-ca371c4c90bc.png)

**Comment by PurcellH** [comment]
![image](https://user-images.githubusercontent.com/38977042/44624989-f132de80-a92f-11e8-90dd-6b0c3bbe0382.png)

**Comment by PurcellH** [comment]
怎么回事？

**Comment by jhao104** [comment]
useful_proxy才是可用代理
