### ISSUE TITLE
关于useful_proxy一直为0的一个解决方法

### ISSUE THREAD

**Issue by Kelaxon** [jhao104/proxy_pool#172]
![image](https://user-images.githubusercontent.com/19503195/44793464-e5b61080-abd8-11e8-846e-706ead74da0c.png)

一开始研究了半天为啥useful_proxy一直是0，以为是验证函数处出错了，结果发现log好像也正常，把验证网站从httpbin改成baidu也是不行。

![image](https://user-images.githubusercontent.com/19503195/44793547-1c8c2680-abd9-11e8-9087-477baa7b5ab0.png)

最后把redis中的raw_proxy拿出来自己验证能否使用，
![image](https://user-images.githubusercontent.com/19503195/44793588-39c0f500-abd9-11e8-998e-5fcfec3bd44f.png)

果然都是用不了的啊 😅

![image](https://user-images.githubusercontent.com/19503195/44793631-4d6c5b80-abd9-11e8-9544-d9d38eb080fe.png)

是不是提供代理的网站都太旧了呃

**Comment by jhao104** [comment]
你得raw_proxy怎么堆积了怎么多 是不是验证程序挂掉了。 如果都不能用ProxyRefreshSchedule.py会一一验证不能用的会从raw_proxy中移除

**Comment by Kelaxon** [comment]
`Schedule`>`ProxyValidSchedule.py`这个文件代码好像有点问题：
67行的`self.proxy_item = self.db.getAll()`是从`useful_proxy`表中拿的，因为还没有验证所以一直都是空的，不断重复While True循环中的`else`部分，然后不断输出`'Valid Complete! sleep 5 minutes.'`

第64行 `self.db.changeTable(self.useful_proxy_queue)` 我改成了 `self.db.changeTable(self.raw_proxy_queue)`之后，`checkProxy.py`才能从`raw_proxy`表中拿出proxy一个个check：

![image](https://user-images.githubusercontent.com/19503195/44825569-bf768c00-ac3d-11e8-905f-05e667929df4.png)

然而ProxyGetter的大部分网站我一个个试了，拿回来的代理都是validation fail的
![image](https://user-images.githubusercontent.com/19503195/44826055-ec2ba300-ac3f-11e8-996a-ace54ca1f411.png)

但是我看了下`ProxyValidSchedule.py`这个文件的历史，发现一直都是这么写的，不知道为啥其他人又能运行呢？😃

**Comment by zhangchj9** [comment]
大概半年前，我运行这个项目的时候其实是没问题的。
然后我刚刚去试了，却也遇到同样的问题，它不能?完成验证操作，就一直堆在raw_proxy，然后改了那句代码之后，就全部验证失败，可能有点问题 @Kelaxon

**Comment by Kelaxon** [comment]
@jhao104 @zhangchj9 我想我已经找到原因了
有几个网站一直报错重连，耽误了很多时间，所以程序一直运行不到`ProxyRefreshSchedule`的部分

![image](https://user-images.githubusercontent.com/19503195/45132075-24902b80-b1c2-11e8-9285-6ac6e7c7d37e.png)
![image](https://user-images.githubusercontent.com/19503195/45132615-2bb83900-b1c4-11e8-96ba-f0e6e0464731.png)


解决方法有俩：
1、给`getFreeProxy.py`里的方法都加上`try..except`，而且墙外的3个网站每次get的时候还要加上timeout，这样每次要等大概5分钟就能得到`useful_proxy`了
![image](https://user-images.githubusercontent.com/19503195/45132047-0296a900-b1c2-11e8-88f0-683bef1f7269.png)

2、直接注释`ProxyRefreshSchedule.py`第80行，这样就不用每次运行`main.py`，明明redis中有很多`raw_proxy`，还要运行这么久再验证咯，可以一直不断验证。
![image](https://user-images.githubusercontent.com/19503195/45131854-56ed5900-b1c1-11e8-86d1-8e28ed7f5235.png)



比心 ❤️

**Comment by zhangchj9** [comment]
freeProxyNinth
freeProxyWallFirst
freeProxyWallSecond
freeProxyWallThird
以上四个免费ip代理网站都不能用了（网络环境为CCTV企业用网/北京联通），访问不了......
出现代理抓取异常而无法正常进入代理验证流程时，大大@Kelaxon 提供的方法亲测可用。
**但如果想偷懒的话**，直接**在Config.ini里注释掉命令行中显示的，连接超时的代理网站所对应的函数名**(在getFreeProxy.py中查找匹对)就行了。

**Comment by xingzhicn** [comment]
@Kelaxon 大大的代码亲测可用，不过好多免费ip代理好像真的不能用了：）
