### ISSUE TITLE
如何添加scheme属性？

### ISSUE THREAD

**Issue by DataScientistSamChan** [jhao104/proxy_pool#18]
1. 第一次用NosqlDb，发现这特别确实比起传统的数据库更适合做这份工作(代理池维护)。
2. 现在我需要给每个ip添加一个scheme属性，我注意到你的数据库工厂类DbClient里面写到value是None，我觉得这应该就是可以放scheme的地方。
3. 我很熟悉怎么抓取数据
4. 我想问一下，应该怎么修改代码来减少工作量，以下是我的想法。

在网页抓取代理IP的时候判断其scheme并添加进SSdb的value，这样的话，工厂类可能也要改，ProxyManager也要改。

请问一下这种情况下的Best practice是什么？

**Comment by DataScientistSamChan** [comment]
说一下我最新的想法，直接复制整个项目目录，一个项目单独抓取HTTP，一个单独抓取HTTPS，这是我想到的最省力的方法，但我觉得这很不专业。不过项目赶，没时间，只能先这样做。

**Comment by jhao104** [comment]
给每个ip加属于是后面要计划的，你的想法是对的。
但是不需要修改DbClient,如果你是用SSDB的话只需要修改SsdbClinet里面的get/post/getAll方法即可。
我们正式项目就是用的SSDB，代理有属性的，用的ssdb的hash存储
