### ISSUE TITLE
直接运行run下的main，然后localhost:5010/get 一直是no proxy

### ISSUE THREAD

**Issue by RockyHoo1209** [jhao104/proxy_pool#182]
控制台有输出ip,但是网页上同通过api查看就是no proxy。代码没改过，测试网站能get到。

**Comment by RockyHoo1209** [comment]
好像突然又可以了，是不是应该和网站访问的速度有关？

**Comment by jhao104** [comment]
@RockyHoo1209 应该代理网站比较多，而且有些网站反应很慢，程序上是要等所有抓取完成才入库，所以只要没报错，等一等才会有代理入库，具体参见：https://github.com/jhao104/proxy_pool/issues/172

**Comment by RockyHoo1209** [comment]
好的谢谢
