### ISSUE TITLE
可不可以实时打印信息？

### ISSUE THREAD

**Issue by JoffreyN** [jhao104/proxy_pool#183]
可不可以实时打印信息，而不是等一个函数运行完后再打印这个函数的运行结果

**Comment by jhao104** [comment]
@JoffreyN 你是指抓代理部分吗？确实是哪一个打印一个呀，只是入库是全部抓取完毕再入库的

**Comment by JoffreyN** [comment]
@jhao104 我是说抓到一条就打印一条，而不是一次打印一个函数的抓取结果，这样要修改所有的抓取函数，好像有点麻烦

**Comment by jhao104** [comment]
没理解你说的意思

**Comment by JoffreyN** [comment]
@jhao104 (* ￣︿￣)
