### ISSUE TITLE
求个docker

### ISSUE THREAD

**Issue by Jinnrry** [jhao104/proxy_pool#185]
可以大佬有部署好的docker？求分享一个，不是专门的运维，也不是flask开发人员，想把这个项目部署到nginx下面，折腾了老半天都不成功

**Comment by YeClimEric** [comment]
> 可以大佬有部署好的docker？求分享一个，不是专门的运维，也不是flask开发人员，想把这个项目部署到nginx下面，折腾了老半天都不成功

docker pull docker.io/yeclimeric/proxy_pool

**Comment by jiangwei1995910** [comment]
@YeClimEric 多谢多谢

**Comment by Crescentz** [comment]
现在这个搜不到了
