### ISSUE TITLE
运行mian.py出错

### ISSUE THREAD

**Issue by liujunfeng941225** [jhao104/proxy_pool#186]
<img width="787" alt="default" src="https://user-images.githubusercontent.com/6049073/46570924-d9269400-c99e-11e8-9ab2-fc9377199104.png">

**Comment by liujunfeng941225** [comment]
就是按照博客中的步骤一步一步来的 求问这该怎么解决？

**Comment by jhao104** [comment]
数据库配置错误 连不上

**Comment by costa92** [comment]
你是连接redis失败
