### ISSUE TITLE
maximum number of running instances reached 

### ISSUE THREAD

**Issue by JoffreyN** [jhao104/proxy_pool#187]
WARNING:apscheduler.scheduler:Execution of job "main (trigger: interval[0:10:00], next run at: 2018-10-08 16:00:59 CST)" skipped: maximum number of running instances reached (1)

----------------------------------------
什么鬼 不动了 一直这样

**Comment by jhao104** [comment]
任务调度间隔时间超过了任务单次运行时间

**Comment by JoffreyN** [comment]
@jhao104 怎么解决啊 大佬

**Comment by jhao104** [comment]
@JoffreyN 那个是运行一次抓取，你配置的抓取函数太多，或者有些网站卡主很久都不返回数据，又或者有些代理网站已经废了。导致运行时间超过10分钟，注释掉耗时的就行了
自己到getFreeProxy里面测试那些是不能用的

**Comment by jhao104** [comment]
所有

**Comment by JoffreyN** [comment]
@jhao104 可以修改任务调度间隔时间吗

**Comment by JoffreyN** [comment]
@jhao104 
哎……我是直接下载的代码运行的，没有任何修改，抓取的网站也都能很快打开，为啥也会这样呢
