### ISSUE TITLE
useful_proxy一直是0

### ISSUE THREAD

**Issue by littleheary** [jhao104/proxy_pool#188]
控制台运行起来了，但是useful_proxy一直是0。
还有就是，请问这个代理池跑起来以后，我在浏览器里使用api的地址作为代理ip地址么？我就可以实现自动切换了么？

**Comment by littleheary** [comment]
控制台一直在提示connection refused。
2018-10-09 21:03:46,735 ProxyValidSchedule.py[line:59] INFO Valid Complete! sleep 5 minutes.
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
2018-10-09 21:04:26,507 ProxyManager.py[line:47] INFO freeProxyWallSecond: fetch proxy start
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ebd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e250>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e710>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ebd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ee10>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e150>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ef50>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e710>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e750>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ec50>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-10-09 21:08:46,771 ProxyValidSchedule.py[line:59] INFO Valid Complete! sleep 5 minutes.
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e910>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ebd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ef90>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e910>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64eb10>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64ed90>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64e150>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64eed0>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPSConnectionPool(host='proxy-list.org', port=443): Max retries exceeded with url: /english/index.php?p=4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc5cf64eb10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by YeClimEric** [comment]
> 控制台运行起来了，但是useful_proxy一直是0。
> 还有就是，请问这个代理池跑起来以后，我在浏览器里使用api的地址作为代理ip地址么？我就可以实现自动切换了么？

优化代码已提交，待作者 merge，merge 后可以在1min 内出现可用代理。使用方法为：
