### ISSUE TITLE
关于代理IP验证

### ISSUE THREAD

**Issue by yimi88** [jhao104/proxy_pool#19]
举例：我要爬取万方数据知识服务平台的数据，代理IP采集+验证完毕但是，有如下的IP，有的IP（115.28.169.160:8118）在使用的过程中采集的数据总总是音悦台http://www.yinyuetai.com/的数据，还有猪八戒http://www.zbj.com/的首页，这样的问题你是咋解决的

**Comment by jhao104** [comment]
没明白你的意思，你意思是用某个ip去访问万方返回的页面确实音悦台的吗
