### ISSUE TITLE
想要修改验证地址怎么改？

### ISSUE THREAD

**Issue by kjxy** [jhao104/proxy_pool#194]
我看以前的问题里，好像代理的验证地址是httpbin.com想改一下，但是看了一圈文件，没找到在哪改...

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L91-L105

**Comment by kjxy** [comment]
> [proxy_pool /的Util / utilFunction.py](https://github.com/jhao104/proxy_pool/blob/edac60ce8ea6340834e1e4afa53d37f3e1a783a8/Util/utilFunction.py#L91-L105)
> 
> [edac60c中的](/jhao104/proxy_pool/commit/edac60ce8ea6340834e1e4afa53d37f3e1a783a8) 第91到105 [行](/jhao104/proxy_pool/commit/edac60ce8ea6340834e1e4afa53d37f3e1a783a8)
> 
>  def  validUsefulProxy（proxy）：
>      “”” 
>      检验代理是否可用 
>      ：param代理： 
>      ：返回： 
>      “”” 
>      if  isinstance（代理，字节）：
>          proxy = proxy.decode（' utf8 '）
>      proxies = { “ http ”：“ http：// {proxy} ”。 format（proxy = proxy）}
>      尝试：
>          ＃超过20秒的代理就不要了 
>          [R = requests.get（' http://httpbin.org/ip '，代理=代理，超时= 10，验证= 假）
>          如果 r.status_code ==  200：
>              # logger.info（'％s is ok'％proxy） 
>              返回 True

感谢~
