### ISSUE TITLE
http 和https的区别

### ISSUE THREAD

**Issue by ZXsilence** [jhao104/proxy_pool#195]
你好，我想请教下ip代理 有两种 http 和https， 那么这两种ip代理有什么区别没？
比如 我用https的代理 请求http的网页，用http的代理请求https的网页？
btw：主要是看到这个项目里面没有区分这个

**Comment by jhao104** [comment]
见 https://github.com/jhao104/proxy_pool/issues/156

**Comment by jhao104** [comment]
已更新
