### ISSUE TITLE
是否可以给代理添加一个类型

### ISSUE THREAD

**Issue by NeoZion** [jhao104/proxy_pool#196]
完全不知道是socks5代理，还是http或者https代理

**Comment by 1again** [comment]
@NeoZion 
hello, https的代理可以看下[高可用代理池服务](https://github.com/1again/ProxyPool)

但同样不支持socks5的代理, 因为目前互联网上所有开放的代理都是基于http/https的.

socks5的开放代理本身比较少, 其实都是有强制验证的, 所以socks5的代理基本上碰不到!
