### ISSUE TITLE
最新版本更新后出现 GDK问题

### ISSUE THREAD

**Issue by yswcdmm** [jhao104/proxy_pool#198]
程序更新后，运行出现以下问题 
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 711: illegal
multibyte sequence

**Comment by JaeLiiin** [comment]
同样出现这样的问题，求解。

**Comment by jhao104** [comment]
@yswcdmm @JaeLiiin 把配置文件里面的中文删掉

**Comment by jhao104** [comment]
有raw_proxy和use_proxy两种，接口返回后者
