### ISSUE TITLE
可用代理好像不会再检测可用性并删除呢？

### ISSUE THREAD

**Issue by kjxy** [jhao104/proxy_pool#199]
昨天运行了几个小时，可用代理数量只增不减，质量应该没有这么好...

用的验证网站是weixin.sougou.com，也有可能是验证网站的原因....现在判断不好，因为我本地ip也可以访问验证网站

**Comment by jhao104** [comment]
> 昨天运行了几个小时，可用代理数量只增不减，质量应该没有这么好...
> 
> 用的验证网站是weixin.sougou.com，也有可能是验证网站的原因....现在判断不好，因为我本地ip也可以访问验证网站

你看下是不是检验方式不对，RefreshSchduler会定时指定检测方法，需要确保代理失效返回Flase，有用返回True

**Comment by kjxy** [comment]
> > 昨天运行了几个小时，可用代理数量只增不减，质量应该没有这么好...
> > 用的验证网站是weixin.sougou.com，也有可能是验证网站的原因....现在判断不好，因为我本地ip也可以访问验证网站
> 
> 你看下是不是检验方式不对，RefreshSchduler会定时指定检测方法，需要确保代理失效返回Flase，有用返回True

验证网站是httpbin.org的时候，有效代理就有增有减，我再看看，3Q~

**Comment by 1again** [comment]
别随便找一个网站做验证, 大部分的网站会封IP的.
因为流量太大了, 会直接封IP的
