### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by winniesi** [jhao104/proxy_pool#2]
Manager.ProxyManager 18行有个拼写错误

from ProxyGetter.GetFreeProxy import GetFreeProxy
==》
from ProxyGetter.getFreeProxy import GetFreeProxy

**Comment by jhao104** [comment]
感谢指教，已改正。有兴趣以后可以一起搞这个

**Comment by winniesi** [comment]
嗯嗯，感谢回复。
教程里面貌似有点小问题哦。

原文：
到Schedule目录下:
python ProxyRefreshSchedule.py

直接运行这个文件导致它本身成为 __main__，导致无法导入上个文件夹的包。如果直接使用代码似乎跑不通。

建议教程改成：
python -m Schedule.ProxyRefreshSchedule

**Comment by jhao104** [comment]
感谢，缺失时间仓促。很多东西待完善改进。
你可以Fork了提交你的更改

**Comment by starry133** [comment]
Util/GetConfig.py 28行有一点问题
self.config_path = os.path.join(os.path.split(self.pwd)[0], 'config.ini')
这里的'config.ini'和主目录里'Config.ini' 名称不一致，运行报错

**Comment by jhao104** [comment]
感谢，已改
