### ISSUE TITLE
还在持续维护吗？

### ISSUE THREAD

**Issue by hhhaiai** [jhao104/proxy_pool#200]

**Comment by hhhaiai** [comment]
> 怎么没人呢。 hiwoshixiaoyu@163.com 发件人： sanbo 发送时间： 2018-10-17 10:50 收件人： jhao104/proxy_pool 抄送： Subscribed 主题： [jhao104/proxy_pool] 还在持续维护吗？ (#200) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

什么？

**Comment by jhao104** [comment]
什么没人

**Comment by hhhaiai** [comment]
> 什么没人

提个建议，能不能一键部署。部分接口可以抄送到你的服务器

**Comment by hhhaiai** [comment]
我们这边后续可能部署服务器做爬虫的工作。 但是不打算对外，可以把部署后的结果抄送你一份给你
