### ISSUE TITLE
新版本 多线程下 会囤积大量IP不验证

### ISSUE THREAD

**Issue by yswcdmm** [jhao104/proxy_pool#201]
现在我获取的IP代理网站有18个 会导致像图片的问题 囤积了1W9IP了可用不多
![p k vtl8xkh7 x qgr qgp7](https://user-images.githubusercontent.com/34054640/47251598-c06eb180-d467-11e8-9873-4e4a2e7702fe.png)

**Comment by uhe1231** [comment]
看看有没有错误日志.
提供下os version, python version

**Comment by jhao104** [comment]
@yswcdmm 
`scheduler.add_job(fetch_all, 'interval', minutes=10)  # 不用太快, 网站更新速度比较慢, 太快会加大验证压力, 导致raw_proxy积压`

**Comment by likenji** [comment]
@jhao104  我也是碰到了这个问题，已经囤积了5000+了，但是即便像你所说地修改（甚至还改过60分钟），raw_proxy仍然不见减少。
有什么比较简单的解决办法吗？

**Comment by jhao104** [comment]
@likenji  拉下现在的master上版本

**Comment by yswcdmm** [comment]
> @ jhao104 我也是碰到了这个问题，已经囤积了5000+了，但是即便像你所说地修改（甚至还改过60分钟），raw_proxy仍然不见减少。
> 虽然可用IP 300 +，但这么一直囤着也担心影响性能。
> 有什么比较简单的解决办法吗？

先将囤积的IP删除，调整好获取时间，我有18个IP代理网站获取时间较长。这样就不会出现以前的问题了。我设置了15分钟的时间。可用大概可以到3000+了
