### ISSUE TITLE
为什么短时间内连续多次请求get接口获得的代理地址一样？

### ISSUE THREAD

**Issue by kngxscn** [jhao104/proxy_pool#204]
看代码里确实用了random函数，但是短时间内连续多次请求get接口，获得的代理地址却一样，get_status查看可用IP并非只有一个

**Comment by mocyx0** [comment]
这是为啥呢，我不懂flask，先加个seed用着把
```
    def get(self):
        """
        return a useful proxy
        :return:
        """
        self.db.changeTable(self.useful_proxy_queue)
        item_dict = self.db.getAll()
        if item_dict:
            if EnvUtil.PY3:
                tm = datetime.datetime.now()
                random.seed(tm)
                return random.choice(list(item_dict.keys()))
            else:
                return random.choice(item_dict.keys())
        return None
        # return self.db.pop()
```

**Comment by Canon88** [comment]
确实啊 我也存在这个问题...

**Comment by kngxscn** [comment]
> 这是为啥呢，我不懂flask，先加个seed用着把
> 
> ```
>     def get(self):
>         """
>         return a useful proxy
>         :return:
>         """
>         self.db.changeTable(self.useful_proxy_queue)
>         item_dict = self.db.getAll()
>         if item_dict:
>             if EnvUtil.PY3:
>                 tm = datetime.datetime.now()
>                 random.seed(tm)
>                 return random.choice(list(item_dict.keys()))
>             else:
>                 return random.choice(item_dict.keys())
>         return None
>         # return self.db.pop()
> ```

 目前我用了个比较粗暴的方式解决这个问题，利用另一个get_all接口
```Python
random.seed(datetime.datetime.now())
proxy = random.choice(requests.get("http://host:port/get_all/").json())
```

**Comment by 1again** [comment]
折腾了一晚上, 找到问题了, 把配置文件`Config.ini`的`processes`字段设置为1
猜测是在多进程的情况下, 每次执行的随机值都一样.

**Comment by jhao104** [comment]
> 折腾了一晚上, 找到问题了, 把配置文件`Config.ini`的`processes`字段设置为1
> 猜测是在多进程的情况下, 每次执行的随机值都一样.

666啊

**Comment by Canon88** [comment]
牛！感谢分享

发自我的 iPhone
