### ISSUE TITLE
InsecureRequestWarning问题怎么解决

### ISSUE THREAD

**Issue by SophieGuan** [jhao104/proxy_pool#21]
运行python -m Schedule.ProxyRefreshSchedule的时候出现了以下问题：
/Users/kanetsu/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
该如何解决呢？

**Comment by jhao104** [comment]
把[ProxyRefreshSchedule.py40](https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py#L40)的https注释掉

**Comment by SophieGuan** [comment]
注释掉了，还是不行。。我看那个connectionpool文件里面有这样一些代码：
   if not conn.is_verified:
            warnings.warn((
                'Unverified HTTPS request is being made. '
                'Adding certificate verification is strongly advised. See: '
                'https://urllib3.readthedocs.io/en/latest/security.html'),
                InsecureRequestWarning)
不知道是什么意思

**Comment by jhao104** [comment]
哦，那就是[这里](https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py#L42)的锅， verfiy改为True

**Comment by SophieGuan** [comment]
解决啦，感谢及时回复！！！
