### ISSUE TITLE
开启代理池后一段时间,响应速度特别慢

### ISSUE THREAD

**Issue by ghost** [jhao104/proxy_pool#213]
开启代理池后一段时间,响应速度特别慢，请求获取IP接口速度特别特别慢

**Comment by 1again** [comment]
1. 一段时间是多久,
2. 特别慢是多久
3. 其他接口也会特别特别慢吗

因为会开多线程去啦代理和校验, 
所以可能会有影响, 判断下是不是这个原因导致的!

**Comment by CHZZBECK** [comment]
就是半小时~一小时，如果用外网获取IP的话就很慢了，卡到10s左右一个，但是我现在换成内网访问就可以了

**Comment by 1again** [comment]
这样是不是你网络的问题, 如果是服务的问题, 使用外网和内网应该是一样的.

**Comment by ayonliu** [comment]
我也遇到同样的问题，内外都很慢，几十秒才返回

**Comment by 1again** [comment]
CPU占用高吗?

**Comment by ayonliu** [comment]
配合 gunicorn 使用，跑了一晚上，慢的问题暂时没有再出现

**Comment by 1again** [comment]
所以很慢的时候cpu高吗？
API这块都是独立的进城再跑，
不会因为抓取代理和验证代理而受到影响！
如果cpu不高，那就是DB卡住了。
但是redis或者ssdb是内存的型的DB这么一点并发不会影响到性能.
所以是mongodb吗？

**Comment by ayonliu** [comment]
慢的时候CPU的情况没注意，DB 用的是 redis。

**Comment by CHZZBECK** [comment]
> 配合 gunicorn 使用，跑了一晚上，慢的问题暂时没有再出现

方便说下怎么使用吗？

**Comment by jhao104** [comment]
> > 配合 gunicorn 使用，跑了一晚上，慢的问题暂时没有再出现
> 
> 方便说下怎么使用吗？

就是单独启动api， 文档里面有写: 
>依次到Api下启动ProxyApi.py,Schedule下启动ProxyRefreshSchedule.py和ProxyValidSchedule.py即可

其中用gunicorn启动api:
`gunicorn ProxyApi:app -w 4 -b 0.0.0.0:5010 --access-logfile /var/log/gunicorn/access_log -D`

**Comment by CHZZBECK** [comment]
> > > 配合 gunicorn 使用，跑了一晚上，慢的问题暂时没有再出现
> > 
> > 
> > 方便说下怎么使用吗？
> 
> 就是单独启动api， 文档里面有写:
> 
> > 依次到Api下启动ProxyApi.py,Schedule下启动ProxyRefreshSchedule.py和ProxyValidSchedule.py即可
> 
> 其中用gunicorn启动api:
> `gunicorn ProxyApi:app -w 4 -b 0.0.0.0:5010 --access-logfile /var/log/gunicorn/access_log -D`

下载gunicorn直接用命令启动吗

**Comment by jhao104** [comment]
> > > > 配合 gunicorn 使用，跑了一晚上，慢的问题暂时没有再出现
> > > 
> > > 
> > > 方便说下怎么使用吗？
> > 
> > 
> > 就是单独启动api， 文档里面有写:
> > > 依次到Api下启动ProxyApi.py,Schedule下启动ProxyRefreshSchedule.py和ProxyValidSchedule.py即可
> > 
> > 
> > 其中用gunicorn启动api:
> > `gunicorn ProxyApi:app -w 4 -b 0.0.0.0:5010 --access-logfile /var/log/gunicorn/access_log -D`
> 
> 下载gunicorn直接用命令启动吗

对滴 [Gunicron文档](http://docs.gunicorn.org/en/latest/install.html)
