### ISSUE TITLE
python 3.6 missing 1 required positional argument: 'username'

### ISSUE THREAD

**Issue by liuxthu** [jhao104/proxy_pool#214]
您好，运行时，提示missing 1 required positional argument: 'username'
并且访问api时无法连接，烦请指导

**Comment by jhao104** [comment]
> 您好，运行时，提示missing 1 required positional argument: 'username'
> 并且访问api时无法连接，烦请指导
拉tags下面的代码，修改配置文件（不要有中文字符）再启动

**Comment by liuxthu** [comment]
> > 您好，运行时，提示missing 1 required positional argument: 'username'
> > 并且访问api时无法连接，烦请指导
> 
> 拉tags下面的代码，修改配置文件（不要有中文字符）再启动

self.client = getattr(__import__(__type), __type)(name=config.db_name,
                                                          host=config.db_host,
                                                          port=config.db_port,
                                                          username='',
                                                          password=config.db_password)
我在这个类里，添加了wh username=''，可以解决了。谢谢哈
