### ISSUE TITLE
作者请进: 关于fork proxy_pool项目的权益问题.

### ISSUE THREAD

**Issue by 1again** [jhao104/proxy_pool#217]
先感谢作者创建了一个很好的项目.

我对项目有一些不同的想法, 

可能更倾向于提供一个`优质的` `灵活的`代理池服务

而不是做为通用的代理池框架, 

因为我觉得框架层的东西会把精力放在了兼容上, 从而忽略了用户的体验.

所以我fork了proxy_pool的项目改名为[ProxyPool](https://github.com/1again/ProxyPool)

目标在于提供`优质的`, `灵活的`代理池服务

但我不只很清楚这个行为是否侵犯了你的权益.(我在网上查询MIT是不会的)

所以在这里咨询下你有什么意见吗?

以上

**Comment by jhao104** [comment]
没问题，开源的部分并不贪图什么利益，分享出来大家共同进步，如果你要用于商业化，其实和我个人利益没有什么冲突，祝好

**Comment by 1again** [comment]
好的，结帖，谢谢！
