### ISSUE TITLE
一个ubuntu配置mongoDB可能的小坑

### ISSUE THREAD

**Issue by likenji** [jhao104/proxy_pool#218]
如果使用apt-install get mongodb来安装MongoDB的话，默认的版本号是2.6。该版本不兼容目前库中代码使用的pop中含有$sample的用法。
需要安装3.X/4.X。
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by 1again** [comment]
hello, 这个确实是的.
默认都是兼容高版本的, 因为低版本有很多bug.
所以使用起来会不安全.

其次你如果在linux环境下.
可以使用`docker/docker-compose`来开发/部署.
不需要折腾这些东西.

**Comment by likenji** [comment]
邮件已到账。我会尽快回复的
