### ISSUE TITLE
www.mimiip.com 无法连接 造成整个进程垮掉

### ISSUE THREAD

**Issue by sicaboy** [jhao104/proxy_pool#219]
2018-11-19 10:16:56,186 ProxyValidSchedule.py[line:59] INFO Valid Complete! sleep 5 minutes.
HTTPConnectionPool(host='www.mimiip.com', port=80): Max retries exceeded with url: /gngao/4 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7473e8110>, 'Connection to www.mimiip.com timed out. (connect timeout=30)'))
HTTPConnectionPool(host='www.mimiip.com', port=80): Max retries exceeded with url: /gngao/4 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7473e8090>, 'Connection to www.mimiip.com timed out. (connect timeout=30)'))
HTTPConnectionPool(host='www.mimiip.com', port=80): Max retries exceeded with url: /gngao/5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb7473d1c10>, 'Connection to www.mimiip.com timed out. (connect timeout=30)'))

**Comment by jhao104** [comment]
@sicaboy 不能使用代理网站自行在配置文件中注释掉， 代理获取方法最好加上try except
