### ISSUE TITLE
用redis当数据库报错

### ISSUE THREAD

**Issue by wwpstl** [jhao104/proxy_pool#221]
eturn self.config_file.get('DB', 'password', fallback=None)
TypeError: get() got an unexpected keyword argument 'fallback'

![image](https://user-images.githubusercontent.com/20418359/48823740-fbcd0a80-ed9c-11e8-991f-06e0e8f28dd0.png)

我的redis没有密码

**Comment by wwpstl** [comment]
解决了。配置文件里写成password=
然后去掉fallback参数

**Comment by 1again** [comment]
你是用的python2.7吗? 我看python3.6上才有这个参数

**Comment by 1again** [comment]
@jhao104 这里为什么要加个fallback的参数? 默认不是None吗?

**Comment by jhao104** [comment]
> @jhao104 这里为什么要加个fallback的参数? 默认不是None吗?

给password默认值none, 否则`self.config_file.get('DB', 'password')`会抛keyerror

**Comment by 4lwin** [comment]
@jhao104 @wwpstl python2.7 SSDB数据库，也遇到同样的问题？
`TypeError: get() got an unexpected keyword argument 'fallback'`

**Comment by 1again** [comment]
python2.7没做兼容处理, 你可以把fallback参数去掉
