### ISSUE TITLE
可否设置代理池维护数量

### ISSUE THREAD

**Issue by AngusWG** [jhao104/proxy_pool#222]
有时候可能5 - 10 条代理就满足需要了  
 如果能在Config.ini 中配置ip最大数量就完美了

**Comment by 1again** [comment]
貌似作者目前没有时间和精力来开发新功能.
冒死来打广告, 你可以看看 [高质量,高灵活的代理池服务](https://github.com/1again/ProxyPool).
里面有你要的功能.

**Comment by jhao104** [comment]
@AngusWG 小众的需求自己改造吧
