### ISSUE TITLE
新人弱弱问下，MongoDB要怎么配置

### ISSUE THREAD

**Issue by yanrs17** [jhao104/proxy_pool#223]
我的MongoDB URI如下：
`mongodb://admin:admin123@ds125841.mlab.com:25841/proxy`
我把`config.ini`改成了
```
type = MONGODB
host = ds125841.mlab.com
port = 25841
name = proxy
username = admin
password = admin123
```
然后他说
`pymongo.errors.OperationFailure: there are no users authenticated`
我已经加了对应的admin和密码，这里no users authenticated要怎么解決

**Comment by 1again** [comment]
因为redis的验证是没有用户名的.
所以没有兼容mongodb用户名.
解决方法:
1. 你可以去掉mongodb验证.
2. 使用redis
3. 自己修改

3.1 `proxy_pool/DB/DbClient.py:78`行, 添加一行
```
username=config.db_username
```
3.2 `proxy_pool/Util/GetConfig.py:47`行, 添加一个
```
    @LazyProperty
    def db_username(self):
        return self.config_file.get('DB', 'username')
```
4. 如果觉得麻烦, 可以使用`jhao104/proxy_pool`的分支 [高质量代理池服务](https://github.com/1again/ProxyPool)
