### ISSUE TITLE
代理验证逻辑诡异

### ISSUE THREAD

**Issue by adrianzhang** [jhao104/proxy_pool#238]
我手动更改了Util/utilFunction.py，使得schedule task可以根据我的验证条件，只留下高匿https代理在useful_proxy。然而，代理从raw_proxy拿过去的时候，却不走这个验证，从get_status里可以清楚地看到。当前这个逻辑显得很诡异。代理从raw_proxy 放到useful_proxy里的时候，应该有个很强的验证。

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/223f57d1eb8d243b1d69e28b90a39f0529ec4407/Schedule/ProxyRefreshSchedule.py#L59

**Comment by adrianzhang** [comment]
> [proxy_pool/Schedule/ProxyRefreshSchedule.py](https://github.com/jhao104/proxy_pool/blob/223f57d1eb8d243b1d69e28b90a39f0529ec4407/Schedule/ProxyRefreshSchedule.py#L59)
> 
> Line 59 in [223f57d](/jhao104/proxy_pool/commit/223f57d1eb8d243b1d69e28b90a39f0529ec4407)
> 
>  if (raw_proxy not in remaining_proxies) and validUsefulProxy(raw_proxy):

是的，找到这个代码了。而且我更改的主要是validUsefulProxy函数。诡异在于，更改后，查看get_status，并同时观测proxy_pool运行log(Run/main.py > proxypool.log)，经常有一种情况：当log里fetch结束的时候，raw里面为0，useful里面很多；当log里提示validation结束的时候，raw里为0，useful大大减少。按代码逻辑，这种情况的解释是因为很多代理在5分钟验证之前是验证有效的，5分钟后就失效了。 可是诡异的是，怎么会5分钟后就有那么多失效呢？？

**Comment by adrianzhang** [comment]
好的。谢谢你的回复。
