### ISSUE TITLE
是否可以在api获取ip时增加一个检测机制？

### ISSUE THREAD

**Issue by zhengyajun** [jhao104/proxy_pool#239]
似乎从api取出的ip并没有做检测，导致部分失效的，是不是可以考虑在取出的时候做循环检测？而且这些代理有些不是高匿的吧？我利用httpbin.org做检测部分返回本机ip和代理ip的集合，不能起到匿名的效果，部分是直接跳转到网页，是否可以考虑优化一下检测规则。如果只考虑本地部署，我的仓库中也有一个简版的高匿代理池，欢迎查看和指点

**Comment by jhao104** [comment]
取出的检查有做，可用代理循环验证也有，高匿的修改 参见 https://github.com/jhao104/proxy_pool/issues/169

**Comment by zhengyajun** [comment]
我的意思是对`get api`获取的`ip`做一个即时的可用性检测。取出再检测，可用再返回。源码目前只是统一维护了一个可用队列，对队列中`ip`进行循环检测，但是当队列很长或检测间隔很长时，取出`ip`的可用性就不高了，当然缩短全局循环检测的时间间隔也能达到一样的效果，但是频繁得维护整个队列资源消耗就高了。不过您这项目是在自己的服务器实现得，哪怕10分钟的周期检测配上单一检测，用户多了同样会造成资源消耗增加，成本增加，所以这个事按理来说也应该交给使用者去验证。

**Comment by zhengyajun** [comment]
> 取出的检查有做，可用代理循环验证也有，高匿的修改 参见 #169

我的意思是对`get api`获取的`ip`做一个即时的可用性检测。取出再检测，可用再返回。源码目前只是统一维护了一个可用队列，对队列中`ip`进行循环检测，但是当队列很长或检测间隔很长时，取出`ip`的可用性就不高了，缩短全局循环检测的时间间隔虽然也能达到一样的效果，但频繁得维护整个队列资源消耗会增加不少。   

不过您这项目是公开的，哪怕10分钟的周期检测配上单一检测，用户多了同样会造成资源消耗增加，成本增加，所以这个事按理来说也应该交给使用者去验证。  

但如果是提供统一的代理池模型，我觉得您可以考虑我的建议。

**Comment by zhengyajun** [comment]
> @zhengyajun 在生产情况下， useful_proxy_queue是要不停的检测的，而且建议多起几个进程，取消休眠保证get接口拿到的代理可用，去api处检验会拖慢池子性能

嗯，只要验证程序高并发、短间隔，那就完全没必要做单一验证了
