### ISSUE TITLE
 guobanjia.com的Port也是加密的，所以爬取这个网站的代码需要更新了

### ISSUE THREAD

**Issue by MarkShawn2020** [jhao104/proxy_pool#247]

**Comment by jhao104** [comment]
@ShawnMark 好的 感谢提醒

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/0baa50dd7cac0d2ecc0b91d2e7a6f242e15b7ac1/ProxyGetter/getFreeProxy.py#L124-L146

刚才实验了下， 这段代码能采集到IP，没问题啊

**Comment by ShawnMark** [comment]
IP能采集是没问题，但是PORT是随机数干扰的，真实的PORT是在它的class属性里，可以确认一下。
不过我也好奇，PORT不对的话，这ip也没法用吧

**Comment by mengqin** [comment]
goubanjia的端口现在这个样子的了：

<span class="port DIHHDG">8989</span>

8989是个假端口，这个span标签的class名“port DIHHDG”是加密的端口，解密在javascript里面有个混淆过的函数。要获取这个函数解密后的串才是真端口。

坐等更新
