### ISSUE TITLE
怎么越过快代理的访问返回521和返回的javasciprt代码

### ISSUE THREAD

**Issue by heartyx** [jhao104/proxy_pool#25]
看了你的代码，受益匪浅。但是我复现不了freeProxyFirst(),按照你写的代码，返回的是521和js代码。我用抓包工具也能看到，在访问网站时，首先会给一个根本错误的包，想问一下 ，你是怎么解决的

**Comment by jhao104** [comment]
谢谢，快代理增加了反爬，有动态加密的Cookie。你可以把他注释掉。如何突破快代理的反爬可以参考我这篇博文https://my.oschina.net/jhao104/blog/865966

**Comment by heartyx** [comment]
哇，还没看先夸赞下你～～好厉害啊！要向你学习！代码设计模块化灰常好，真厉害。
先谢谢你的帮助～
