### ISSUE TITLE
为何不用线程启动？

### ISSUE THREAD

**Issue by yizantianxia** [jhao104/proxy_pool#253]
一直以来，您是用多进程的方式启动，为何不用多线程呢？是因为多线程有bug吗？我今天试了下，多线程也可以运行·。
之所以改用多线程，我是想集成到我的django项目里，随django启动而启动，关闭而关闭。
但我还没找到方法，或许您有任何建议吗？谢谢

**Comment by jhao104** [comment]
确实python的线程比较鸡肋。

你可以把启动代码写到django的manage.py 
最好是把他们分开，另写一个py或者start.sh去启动他们
