### ISSUE TITLE
why the useful proxy is too less?

### ISSUE THREAD

**Issue by iamanam** [jhao104/proxy_pool#254]
There used to be a lot of useful proxy, but after updating it - the useful proxy never increase much from 100. Sometime it's as low as 4. Before, it never used to get less than 400-500. I was using it for long time and it never happened until recently. I am using it on Ubuntu server. Currently there are only 87 raw proxy and 14 useful proxy. Any idea why its happening or is it normal?

**Comment by jhao104** [comment]
@iamanam the proxy count depends on [ProxyGetter](https://github.com/jhao104/proxy_pool/blob/master/ProxyGetter/getFreeProxy.py)，some free proxy website disabled now.

on the other hand , i quickening check pace, the proxy count is less and proxy quality more better

**Comment by likenji** [comment]
> @iamanam the proxy count depends on [ProxyGetter](https://github.com/jhao104/proxy_pool/blob/master/ProxyGetter/getFreeProxy.py)，some free proxy website disabled now.
> 
> on the other hand , i quickening check pace, the proxy count is less and proxy quality more better
> 
> [proxy_pool/Schedule/ProxyValidSchedule.py](https://github.com/jhao104/proxy_pool/blob/0c48d9dc1a0e3dcb2f166882ea29ed7ad3213a21/Schedule/ProxyValidSchedule.py#L60)
> 
> Line 60 in [0c48d9d](/jhao104/proxy_pool/commit/0c48d9dc1a0e3dcb2f166882ea29ed7ad3213a21)
> 
>  time.sleep(5)

I think it is better to set this parameter be in setting.py, then  each user can adjust this parameter according to their requirements.

**Comment by iamanam** [comment]
@jhao104  in that case more agent should be added i guess if its possible. Anyway, thanks for the good work.
