### ISSUE TITLE
希望添加返回http和https的api,谢谢！

### ISSUE THREAD

**Issue by 1368129224** [jhao104/proxy_pool#257]
RT,谢谢！

**Comment by harryzcy** [comment]
目前好像 http和https这些数据在数据库里都没有存？

**Comment by jhao104** [comment]
下个版本会有

**Comment by zhang-wangz** [comment]
补充了http，https的类别筛选，同时返回选择为大佬 #441 max最优代理，
效果如下demo: ip.wangz.online/get_http 或者ip.wangz.online/get_https, 一小时内有访问次数限制，可以简单测试
