### ISSUE TITLE
这两个地址的规则该怎么写

### ISSUE THREAD

**Issue by ipanel** [jhao104/proxy_pool#27]
http://proxydb.net/
http://multiproxy.org/cgi-bin/search-proxy.pl
写了几个，就这两个的搞不好。菜鸟求教

**Comment by jhao104** [comment]
这两个网站的代理都可以用正则表达式来提取的

**Comment by ipanel** [comment]
`    @staticmethod
    @robustCrawl
    def freeProxy2():
        """
        :return:
        """
        url_list = ['http://multiproxy.org/cgi-bin/search-proxy.pl?Type=all&TopDomain=all&PortNum=8080&Submit=++Search++']
        for each_url in url_list:
            tree = getHtmlTree(each_url)
            proxy_list = tree.xpath('.//script[@type="text/javascript"]//br/p')
            for proxy in proxy_list:
                yield ':'.join(proxy.xpath('./br/text()')[0])
`
为什么抓取的内容和网页内容不一样

**Comment by ipanel** [comment]
>    @staticmethod
    @robustCrawl
    def freeProxy2():
        """
        :return:
        """
        url_list = ['http://multiproxy.org/cgi-bin/search-proxy.pl?Type=all&TopDomain=all&PortNum=8080&Submit=++Search++']
        for each_url in url_list:
            tree = getHtmlTree(each_url)
            proxy_list = tree.xpath('.//script[@type="text/javascript"]//br/p')
            for proxy in proxy_list:
                yield ':'.join(proxy.xpath('./br/text()')[0])

**Comment by ipanel** [comment]
为什么抓取的内容和网页内容不一样

**Comment by jhao104** [comment]
抓回来的内容和网页内容不一样是爬虫基础问题。
  这个原因有很多，网页可能是JS渲染的、或者对面有防机器人措施。或者被ban掉了

**Comment by ipanel** [comment]
能帮忙写给这个的规则吗
http://proxydb.net/
我第一次接触python不是很会写规则

**Comment by ipanel** [comment]
我写出来的规则用正则获取不到内容

**Comment by jhao104** [comment]
```
@staticmethod
    @robustCrawl
    def freeProxySixth():
        url = "http://proxydb.net/"
        html = requests.get(url, headers=HEADER).content
        proxy_list = re.findall(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}', html)
        for proxy in proxy_list:
            yield proxy
```

**Comment by ipanel** [comment]
报错了

Traceback (most recent call last):
  File "ProxyRefreshSchedule.py", line 87, in <module>
    main()
  File "ProxyRefreshSchedule.py", line 73, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 40, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
AttributeError: type object 'GetFreeProxy' has no attribute 'freeProxySixth'
root@kaifubiao:/home/proxy_pool/Schedule# 
root@kaifubiao:/home/proxy_pool/Schedule# python ProxyRefreshSchedule.py
Traceback (most recent call last):
  File "ProxyRefreshSchedule.py", line 24, in <module>
    from Manager.ProxyManager import ProxyManager
  File "../Manager/ProxyManager.py", line 18, in <module>
    from ProxyGetter.getFreeProxy import GetFreeProxy
  File "../ProxyGetter/getFreeProxy.py", line 135
    proxy_list = re.findall(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}', html)
    ^

**Comment by jhao104** [comment]
> AttributeError: type object 'GetFreeProxy' has no attribute 'freeProxySixth'

你把名字写错了

**Comment by JayeWu** [comment]
目标网站有反爬措施，你获取的是渲染之前的网页，这时没有ip信息。使用webdriver 可以获取渲染后的网页。
![image](https://user-images.githubusercontent.com/27194796/35786938-b03a2028-0a65-11e8-99ad-794291d606bf.png)

**Comment by JayeWu** [comment]
def getHtmlTree(url, **kwargs):
         chromeOptions = webdriver.ChromeOptions();
    # 设置为 headless 模式
    chromeOptions.add_argument("--headless")
    browser = webdriver.Chrome(chrome_options=chromeOptions)
    # browser = webdriver.Chrome()
    browser.get(url)
    time.sleep(2)
    html = browser.page_source
    return etree.HTML(html)

**Comment by JayeWu** [comment]
``def getHtmlTree(url, **kwargs):
       chromeOptions = webdriver.ChromeOptions();
       # 设置为 headless 模式
       chromeOptions.add_argument("--headless")
       browser = webdriver.Chrome(chrome_options=chromeOptions)
       # browser = webdriver.Chrome()
       browser.get(url)
       time.sleep(2)
       html = browser.page_source
       return etree.HTML(html)

**Comment by JayeWu** [comment]
def getHtmlTree(url, **kwargs):
              chromeOptions = webdriver.ChromeOptions();
              # 设置为 headless 模式
              chromeOptions.add_argument("--headless")
              browser = webdriver.Chrome(chrome_options=chromeOptions)
              # browser = webdriver.Chrome()
              browser.get(url)
              time.sleep(2)
              html = browser.page_source
              return etree.HTML(html)
