### ISSUE TITLE
针对特定网站代理被BAN IP的疑问

### ISSUE THREAD

**Issue by Lcatss** [jhao104/proxy_pool#271]
我在做一个访问过快会BAN IP的网站的爬虫，试着修改了validUsefulProxy这个验证函数访问的url，想筛选出针对某个特定网站的代理池。可是发现useful_proxy在ProxyValidSchedule验证几次后会大量被BAN，是因为多线程验证代理会导致同一个代理对该网站发出高并发请求吗？实现特定网站代理池的正确方式应该是怎么样的？

**Comment by 1again** [comment]
这是一个无解的问题.

1. 因为是野代理, 所以质量不可靠.
2. 因为质量不可靠, 所以需要验证.
3. 因为验证所以导致IP被BAN.

需要在验证和BAN之间取一个平衡.

验证方法:
1. 可以在`随机`的时间间隔里访问目标网站上`随机`的页面来得到验证效果.

需要注意:
1. 看看你的http请求头是不是有些不安全的信息, 比如`user-agent`
2. 很多野代理会自动加上Proxy的http头, 导致网站能识别出使用代理的请求.
可以在`http://httpbin.org`上判断!

**Comment by jhao104** [comment]
这种就是你检测的url本身就有反爬机制，换个不检测的，代理池就只需要保证代理能用，被ban的问题应该在你爬虫代码里处理
