### ISSUE TITLE
有用ip越来越多， 达到十几万，感觉有问题 

### ISSUE THREAD

**Issue by EngiGu** [jhao104/proxy_pool#272]
ip会一直增多， 校验规则好像无效了

**Comment by jhao104** [comment]
不是检测无效了，是抓取的频率大于检测的速度，这样就会越积越多，
解决办法：
  每次抓最新的，不要每次抓好几页，后面的基本没有，检测又非常耗时。
  减小timeout时间
  增加检测线程数

**Comment by yubinhong** [comment]
我也有遇到这个问题，程序跑一段时间之后，ip数越来越多，感觉是验证代理没在跑，重启一下程序，ip数一下子就降下来了

**Comment by yubinhong** [comment]
我这边测试了下，是python版本的问题，python2会有问题，python3没有，感觉是在redis连接出了问题
