### ISSUE TITLE
debain8下：python2 -m Run.main报错

### ISSUE THREAD

**Issue by nisiwa** [jhao104/proxy_pool#28]
你好：

使用时：
$:~/proxy_pool/Api$ python2 -m Run.main
$:/usr/bin/python2: No module named Run
请问怎么解决

**Comment by jhao104** [comment]
直接到各个文件夹下启动。比如/proxy_pool/Api 下 启动python run.py

**Comment by nisiwa** [comment]
嗯，之前是这样做的，但是在浏览器下面就只有get能用，其他的要出错。我使用了ssdb，但是只有raw_proxy的记录，这是为何呢？

**Comment by jhao104** [comment]
要启动两个 除了main.py 还有个ProxyRefreshSchedule.py

**Comment by Rafael-Cheng** [comment]
请问我的Api目录下只有ProxyApi.py和__init__.py，无法python -m Run.main和python run.py，应该怎么启动？

**Comment by jhao104** [comment]
在Run目录下运行main.py

**Comment by blackjws** [comment]
你好，github主
运行main函数报错
NoOptionError: No option 'name' in section: 'DB'

**Comment by blackjws** [comment]
你好，github主 报错如下，能帮忙解答一下吗？
(lenv) [kenwood@kenwood proxy_pool]$ python -m Schedule.ProxyRefreshSchedule
No handlers could be found for logger "apscheduler.executors.default"

**Comment by jhao104** [comment]
你是把logging相关注释掉了吗？这个模块要有logging才行

**Comment by blackjws** [comment]
好像不是，我在运行127.0.0.1:5000/get/的时候好像就会报错，运行get_all的时候也没有任何返回

**Comment by jhao104** [comment]
那你试试单独在Api下启动ProxyApi.py
