### ISSUE TITLE
可以换一种验证方式

### ISSUE THREAD

**Issue by hy9125** [jhao104/proxy_pool#31]
用蜜罐  http://httpbin.org/ip  检测速度会更快一点

另外，快代理貌似不用JS渲染了

**Comment by jhao104** [comment]
确实用代理去访问百度的验证速度非常慢，我也想换一种更方便快速的方式。
请问这个网站是什么性质的？可靠吗

**Comment by hy9125** [comment]
算一个开源项目吧  
https://github.com/kennethreitz/httpbin

**Comment by jhao104** [comment]
用这个的话 要检测IP是否可用岂不是要发两次 一次http的和一次https的？https://httpbin.org/ip http://httpbin.org/ip

**Comment by hy9125** [comment]
抱歉，是我没有考虑全
我觉得如果只爬HTTP站点的话用这个会不会好一点，毕竟国内大部分网站都是HTTP

**Comment by jhao104** [comment]
如果你用过这个验证代理IP，而且确实速度比较快的话。这确实是个好的实践。感谢提供这个工具

我是一直想找一个可以快速验证代理的方法，没找到可靠的
