### ISSUE TITLE
有人使用py3.7吗？死活安装不上lxml

### ISSUE THREAD

**Issue by zhyblack** [jhao104/proxy_pool#318]
好像lxml3.7.2就没有支持py3.7的包，

**Comment by q13392** [comment]
去下载wheel文件安装,我也是PIP安装不上

**Comment by kite8** [comment]
使用anaconda, 镜像源用清华的

**Comment by harryzcy** [comment]
我直接 `pip install lxml`
使用过程中目前还没出现问题

**Comment by smwsk** [comment]
参考博客[lxml不含etree模块](https://www.cnblogs.com/shuibingyue/p/7090624.html),
我的python版本是`3.7.1`,下载的非官方whl文件是lxml-4.3.5-cp37-cp37m-win_amd64.whl
