### ISSUE TITLE
在服务器上运行的，但是服务器上没有浏览器，请问怎么访问网页？

### ISSUE THREAD

**Issue by mengguiyouziyi** [jhao104/proxy_pool#32]

**Comment by PythonYXY** [comment]
用requests库访问URL呀

**Comment by mengguiyouziyi** [comment]
就是说我在服务器上爬了ip放入了ssdb库，然后我该怎么用127.0.0.1:5000查看，因为我的服务器是没有浏览器的。

**Comment by PythonYXY** [comment]
仔细看看README.MD

**Comment by jhao104** [comment]
你好,flask是可以监听外网访问的，程序里也是开启的了。如果你正常启动了程序就可以使访问http://服务器ip：5000查看
