### ISSUE TITLE
docker部署之后，获取ip很慢，要几秒钟

### ISSUE THREAD

**Issue by MarsWgl** [jhao104/proxy_pool#320]

**Comment by jhao104** [comment]
检查你网络连通吧，程序到数据库 程序到你浏览器客户端

**Comment by MarsWgl** [comment]
> 检查你网络连通吧，程序到数据库 程序到你浏览器客户端

我只开了api服务，访问 127.0.0.1:5010/ 都很慢，但是有时候却又秒开的。是因为docker的原因吗？

**Comment by jhao104** [comment]
> > 检查你网络连通吧，程序到数据库 程序到你浏览器客户端
> 
> 我只开了api服务，访问 127.0.0.1:5010/ 都很慢，但是有时候却又秒开的。是因为docker的原因吗？

中间网络原因，Docker不会导致这样

**Comment by kingking888** [comment]
Run 文件导入错误，调度文件已经修改------------------ 原始邮件 ------------------
发件人: "J_hao104"<notifications@github.com>
发送时间: 2019年8月15日(星期四) 晚上7:10
收件人: "jhao104/proxy_pool"<proxy_pool@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [jhao104/proxy_pool] docker部署之后，获取ip很慢，要几秒钟 (#320)


  
检查你网络连通吧，程序到数据库 程序到你浏览器客户端
  
我只开了api&#x670D;务，访问 127.0.0.1:5010/ 都很慢，但是有时候却又秒开的。是因为docker的原因吗？
  
中间网络原因，Docker不会导致这样
 
&mdash;
