### ISSUE TITLE
no hclear ??

### ISSUE THREAD

**Issue by kingking888** [jhao104/proxy_pool#324]
def clear(self):
        """
        清空所有代理, 使用changeTable指定hash name
        :return:
        """
        return self.__conn.execute_command("del", self.name)

**Comment by jhao104** [comment]
现在master上的新版 ssdb和redis拆开了，需要单独配置，不能通用，看下文档的配置部分

**Comment by kingking888** [comment]
谢谢大佬------------------ 原始邮件 ------------------
发件人: "J_hao104"<notifications@github.com>
发送时间: 2019年8月16日(星期五) 上午9:55
收件人: "jhao104/proxy_pool"<proxy_pool@noreply.github.com>;
抄送: "Kingking"<184108270@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jhao104/proxy_pool] no hclear ?? (#324)



现在master上的新版 ssdb和redis拆开了，需要单独配置，不能通用，看下文档的配置部分
 
&mdash;
