### ISSUE TITLE
现在这个项目不能运行吧？

### ISSUE THREAD

**Issue by 1060460048** [jhao104/proxy_pool#334]
![QQ截图20190820173548](https://user-images.githubusercontent.com/5127956/63336047-0ab70c80-c371-11e9-8f94-72532fa7a4de.png) (图1)
Main.py文件中有这样的代码：
`from Api.ProxyApi import run as ProxyApiRun
from Schedule.ProxyValidSchedule import run as ValidRun
from Schedule.ProxyRefreshSchedule import run as RefreshRun`
但是实际上Schedule目录下都没有对应的文件
![QQ截图20190820173737](https://user-images.githubusercontent.com/5127956/63336230-5f5a8780-c371-11e9-8d5d-d04078c21fe2.png) （图2）
然后我改了文件的引入，现在报是redis的clear方法不存在，报错如图1；

**Comment by jhao104** [comment]
看文档，启动方式和配置都更新了

**Comment by 1060460048** [comment]
你这个跟原来文档一样啊 Run/main.py中引入的文件在Schedule目录都找不到 我git pull拉了代码，并没有更新，问题依然存在。不知是否为操作的原因。

**Comment by jhao104** [comment]
![image](https://user-images.githubusercontent.com/15058920/63478758-9f2e8580-c4bd-11e9-9c53-6c822b8cb98b.png)

**Comment by hsowan** [comment]
没有更新Dockerfile

**Comment by jhao104** [comment]
dockerfile已更新
```
docker pull jhao104/proxy_pool

docker run --env db_type=REDIS --env db_host=127.0.0.1 --env db_port=6379 --env db_password=pwd_str -p 5010:5010 jhao104/proxy_pool
```
