### ISSUE TITLE
运行python proxyPool.py schedule错误，提示python: can't open file 'proxyPool.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by banzuan** [jhao104/proxy_pool#342]

**Comment by jhao104** [comment]
具体日志贴上来

**Comment by banzuan** [comment]
> 具体日志贴上来

就是提示python: can't open file 'proxyPool.py': [Errno 2] No such file or directory

**Comment by jhao104** [comment]
要么代码版本不对，要么运行位置不对，提示很明显了找不到文件，要到cli目录下

**Comment by zhuhuadeaa** [comment]
莫名其妙的好了…不知道为啥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: J_hao104 <notifications@github.com&gt;
发送时间: 2019年8月29日 19:33
收件人: jhao104/proxy_pool <proxy_pool@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jhao104/proxy_pool] 运行python proxyPool.py schedule错误，提示python: can't open file 'proxyPool.py': [Errno 2] No such file or directory (#342)




要么代码版本不对，要么运行位置不对，提示很明显了找不到文件，要到cli目录下

**Comment by banzuan** [comment]
> 要么代码版本不对，要么运行位置不对，提示很明显了找不到文件，要到cli目录下
没有cli目录啊

**Comment by banzuan** [comment]
> 要么代码版本不对，要么运行位置不对，提示很明显了找不到文件，要到cli目录下

没有cli目录啊

**Comment by banzuan** [comment]
> > 要么代码版本不对，要么运行位置不对，提示很明显了找不到文件，要到cli目录下
> 
> 没有cli目录啊

我知道了，我在relases里面直接下载的没有cli目录
