### ISSUE TITLE
项目文件中存在的问题，包括redis10061解决

### ISSUE THREAD

**Issue by QiuZiXian** [jhao104/proxy_pool#344]
1、api.proxyapi 中的run函数分成两个
2、schedule下的两个文件名也发生变动，对应的run函数也改名
3、db下的ssdbclient的 clear函数有问题（换redis就不用管）

正常使用注意的问题：
（1）redis.exceptions.ConnectionError: Error 10061 ；redis的端口问题，查看自身端口多少，在setting文件中做相应修改
（2）同样需要在setting文件中吧db_type改为redis

**Comment by Atheny** [comment]
还有两处报错的地方
1.  ProxyHelper文件夹下，Proxy.py中的newProxyFromJson方法中，加判断if type(proxy_dict).__name__ == 'dict'：否在报错AttributeError: 'int' object has no attribute 'get'

2. Api文件夹下，ProxyApi.py中的getAll方法中，改为返回return [_.info_dict for _ in proxies if _ is not None]，放在None类型无info_dict的报错。
修改了这两个地方，就能运行了，亲测。

**Comment by jhao104** [comment]
> 还有两处报错的地方
> 
> 1. ProxyHelper文件夹下，Proxy.py中的newProxyFromJson方法中，加判断if type(proxy_dict).**name** == 'dict'：否则报错AttributeError: 'int' object has no attribute 'get'
> 2. Api文件夹下，ProxyApi.py中的getAll方法中，改为返回return [_.info_dict for _ in proxies if _ is not None]，放在None类型无info_dict的报错。
>    修改了这两个地方，就能运行了，亲测。

你那个是因为先用了之前版本，数据存的不是json,升级新版本之前清掉原来的数据库就好了

**Comment by Atheny** [comment]
> 1、api.proxyapi 中的run函数分成两个
> 2、schedule下的两个文件名也发生变动，对应的run函数也改名
> 3、db下的ssdbclient的 clear函数有问题（换redis就不用管）
> 
> 正常使用注意的问题：
> （1）redis.exceptions.ConnectionError: Error 10061 ；redis的端口问题，查看自身端口多少，在setting文件中做相应修改
> （2）同样需要在setting文件中吧db_type改为redis



> > 还有两处报错的地方
> > 
> > 1. ProxyHelper文件夹下，Proxy.py中的newProxyFromJson方法中，加判断if type(proxy_dict).**name** == 'dict'：否则报错AttributeError: 'int' object has no attribute 'get'
> > 2. Api文件夹下，ProxyApi.py中的getAll方法中，改为返回return [_.info_dict for _ in proxies if _ is not None]，放在None类型无info_dict的报错。
> >    修改了这两个地方，就能运行了，亲测。
> 
> 你那个是因为先用了之前版本，数据存的不是json,升级新版本之前清掉原来的数据库就好了

好的，感谢，我试试~

**Comment by Atheny** [comment]
> > 还有两处报错的地方
> > 
> > 1. ProxyHelper文件夹下，Proxy.py中的newProxyFromJson方法中，加判断if type(proxy_dict).**name** == 'dict'：否则报错AttributeError: 'int' object has no attribute 'get'
> > 2. Api文件夹下，ProxyApi.py中的getAll方法中，改为返回return [_.info_dict for _ in proxies if _ is not None]，放在None类型无info_dict的报错。
> >    修改了这两个地方，就能运行了，亲测。
> 
> 你那个是因为先用了之前版本，数据存的不是json,升级新版本之前清掉原来的数据库就好了

确实是以前版本导致的，清除redis数据库中的数据以后，重新启动就没有报错了，感谢提醒！
