### ISSUE TITLE
main报 没有run的错误

### ISSUE THREAD

**Issue by guyuexuehu** [jhao104/proxy_pool#348]

**Comment by jhao104** [comment]
看文档，现在还没main.py了

**Comment by jhao104** [comment]
# 如果你的依赖已经安全完成并且具备运行条件,可以在cli下运行通过ProxyPool.py启动
# 程序分为: schedule 调度程序 和 webserver Api服务

# 首先启动调度程序
>>>python proxyPool.py schedule

# 然后启动webApi服务
>>>python proxyPool.py webserver
