### ISSUE TITLE
执行schedule  出现 “unknown command hclear”错误

### ISSUE THREAD

**Issue by ChenAnZong** [jhao104/proxy_pool#353]
redis已安装最新版本
![image](https://user-images.githubusercontent.com/29799850/65206606-8f589000-dac1-11e9-9740-5fb405298b0f.png)

**Comment by jhao104** [comment]
redis和ssdb单独配，用redis type 配 REDIS

**Comment by ChenAnZong** [comment]
忘了改数据库类型, 感谢
