### ISSUE TITLE
我也有这个错误，必须用0.12吗。我是把requirements里面的版本限制都去了

### ISSUE THREAD

**Issue by song-zhixue** [jhao104/proxy_pool#359]
我也有这个错误，必须用0.12吗。我是把requirements里面的版本限制都去了

_Originally posted by @xmjharry in https://github.com/jhao104/proxy_pool/issues/356#issuecomment-536429516_

我改了falsk版本就好了

**Comment by jhao104** [comment]
其他版本我也没试过，没办法python就是有这个问题，所以推荐还是用anaconda类似的环境管理工具和requirements要求保持一致

**Comment by CYY666666** [comment]
改成str就行

**Comment by jhao104** [comment]
closed by commit [d21c9d1ff55867c335c30be7baec43e50c08ed4c]
