### ISSUE TITLE
调用get时返回服务器内部错误

### ISSUE THREAD

**Issue by SecurityNeo** [jhao104/proxy_pool#36]
使用get_all返回为空，使用get时返回服务器内部错误，这个何解？
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jhao104** [comment]
你用的测试接口吗？应该是代理用光了。。

**Comment by SecurityNeo** [comment]
今天测试接口和我这边都出问题了。看来这个有用的IP并不多哇

**Comment by jhao104** [comment]
当然，免费代理很少的，你也可已自己添加几个免费的网站。最好使买付费api放到这里

**Comment by Mrliduanyang** [comment]
今天也是同样的问题，想问一下，log文件夹下，refresh_schedule.log文件中的那些个ip都是代理ip吗？

**Comment by jhao104** [comment]
是验证代理的日志 有fail的也有pass的

**Comment by xgy666** [comment]
问一下你这个问题解决了吗

**Comment by jhao104** [comment]
@xgy666 是解决了的，你还遇到这个问题了吗？代码是最新的吗

**Comment by yuantkong** [comment]
重新下载,没有改配置, 依旧是这个问题
可以进首页但无法进入 get/get_all
会显示redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:8888. 由于目标计算机积极拒绝，无法连接。.

**Comment by jhao104** [comment]
`redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:8888. 由于目标计算机积极拒绝，无法连接` 这种情况很明显了，检查数据库配置 连不上
