### ISSUE TITLE
我想加一个新的feature

### ISSUE THREAD

**Issue by halleywj** [jhao104/proxy_pool#37]
你好。我在使用你的代码的时候，直接用的存在redis里面的结果。但是代理在useful_proxy_queue中的代理要人为丢掉才会丢掉，但一次失败就丢会导致代理很快用完，所以我使用的时候，在从redis取东西的时候加了判断，连续20次失败了我才正式把它丢了，效果还不错。但是这边主要是加在我的代码逻辑里面，我想把它加在代理池接口部分，不知道这个feature接收吗。

**Comment by jhao104** [comment]
当然是可以的，当时设计的时候给代理留了属性设置的
