### ISSUE TITLE
如何给get 添加筛选条件？

### ISSUE THREAD

**Issue by 5wcx** [jhao104/proxy_pool#386]
我已经搭建好了，项目也在用了，发现有很多check_count=0的不可用，我想要在get 中筛选一下  只输出 check_count > 1的 ，如何改代码啊？ 我也不会修改这个代码？求大大

**Comment by jhao104** [comment]
hash结构是没法搜索的，只能在代码里面去过滤
https://github.com/jhao104/proxy_pool/blob/5349289ff3e5679da7ceb62765ab4212ea40fdfe/Manager/ProxyManager.py#L74-L78
`item_list.filter()`加你过滤条件就行

**Comment by 5wcx** [comment]
item_list = filter(lambda item:json.loads(item)['check_count']>100,self.db.getAll())  改成了这样 感谢大大。
