### ISSUE TITLE
这两天一个代理也跑不出来了？

### ISSUE THREAD

**Issue by hiber-niu** [jhao104/proxy_pool#39]
按照文档说明，安装了依赖包和ｓｓｄｂ，但是执行ｐｙｔｈｏｎ后进程中仅有两个main.py，ｌｏｇ文件中没有任何错误，是哪里出了问题么？

**Comment by jhao104** [comment]
README里提了 如果有问题可以单独跑这三个进程：
`也可以分别运行他们,依次到Api下启动ProxyApi.py,Schedule下启动ProxyRefreshSchedule.py和ProxyValidSchedule.py即可`
