### ISSUE TITLE
数据库可不可以换成纯python实现的Nosql，希望还是直接支持python3的

### ISSUE THREAD

**Issue by fbigun** [jhao104/proxy_pool#4]
数据库可不可以换成纯python实现的Nosql，希望还是直接支持python3的。
python3 现在用的基本上用python3了。

**Comment by jhao104** [comment]
支持python3正在计划中， 不过你说“纯python实现的Nosql”是指什么？ 现在准备支持redis和文件系统

**Comment by fbigun** [comment]
推荐添加CodernityDB数据库。

为什么我使用的时候出现这个错误，我完全按照readme.md部署不能正常使用
`cd Schedule`
`python ProxyRefreshSchedule.py`
```
python ProxyRefreshSchedule.py
Traceback (most recent call last):
  File "ProxyRefreshSchedule.py", line 21, in <module>
    from Manager.ProxyManager import ProxyManager
ImportError: No module named Manager.ProxyManager
```
你这个仅仅只是一个框架，要自己实现启动吗？

**Comment by jhao104** [comment]
启动是有的，之前搜索路劲有问题，改了忘记提交了。
到项目下运行这两个就行
python -m Schedule.ProxyRefreshSchedule
python -m Api.ProxyApi

现在数据库是支持扩展的。DB模块是个工厂模块，可以任意添加其他数据库。

现在计划支持reids和本地文件。

**Comment by fbigun** [comment]
试用了一下这个ssdb，发现这个数据库更好用，决定还是切换了！！！

**Comment by jhao104** [comment]
哈哈 我只从接触ssdb过后就爱不释手了
