### ISSUE TITLE
goubanjia代理获取结果有问题

### ISSUE THREAD

**Issue by garfieldkai** [jhao104/proxy_pool#40]
不知道大家有没有这种情况，goubanjia的代理获取有问题，代理是“222222.9.944.144.9999:8616”这样的

**Comment by garfieldkai** [comment]
我修改了一下freeProxyFifth方法，最近刚接触python，xpath也不熟，改的比较low，但是可以获取正常的代理。
 @staticmethod
    @robustCrawl
    def freeProxyFifth():
        """
        抓取guobanjia http://www.goubanjia.com/free/gngn/index.shtml
        :return:
        """
        url = "http://www.goubanjia.com/free/gngn/index{page}.shtml"
        for page in range(1, 10):
            page_url = url.format(page=page)
            tree = getHtmlTree(page_url)
            proxy_list = tree.xpath('//td[@class="ip"]')
            for each_proxy in proxy_list:
                # yield ''.join(each_proxy.xpath('.//span[not @style="display: none;"]//text()'))
                ips = each_proxy.xpath('.//span[not (@style="display: none;")]//text()|.//div[not (@style="display: none;")]//text()')
                ip = ''.join(ips[0:-1])
                yield ':'.join([ip,ips[-1]])

**Comment by cumtqiangqiang** [comment]
你用的ssdb么？

**Comment by jhao104** [comment]
f5a4317bbc96f6396d85337bba735545c437fecd
