### ISSUE TITLE
Python 3.7 在安装lxml的时候报错

### ISSUE THREAD

**Issue by littlebai3618** [jhao104/proxy_pool#401]
希望升级下依赖包里lxml的版本以支持3.7

**Comment by did999** [comment]
同样遇到这种情况。

**Comment by 7733012** [comment]
我也是3.8.1python ，把requirements.txt 版本改一下，再安装就可以了
如下：
 lxml==4.4.2

**Comment by nrcy** [comment]
我用pip手动安装了一遍，已经解决

**Comment by zhan2cool** [comment]
> 我也是3.8.1python ，把requirements.txt 版本改一下，再安装就可以了
> 如下：
> lxml==4.4.2

3.7.1，right

**Comment by shizia** [comment]
> 我也是3.8.1python ，把requirements.txt 版本改一下，再安装就可以了
> 如下：
> lxml==4.4.2

请问是怎么改的呢？
