### ISSUE TITLE
能不能判断socks5的代理IP?

### ISSUE THREAD

**Issue by leoxzl** [jhao104/proxy_pool#41]
1.能不能判断socks5的代理IP? 
2. 是否可以运行于Python 3.x 版本?

**Comment by jhao104** [comment]
可以运行在py3
判断代理的方法是proxy_pool/Util/utilFunction.py中的validUsefulProxy方法。目前只是检验是否能访问百度

**Comment by Just2co** [comment]
@jhao104 我想用来检测是否可以打开google.com.hk，这样就可以用来作为梯子的前置，我只要把baidu.com这个域名更改成google.co.jp就可以了，是吧

**Comment by jhao104** [comment]
@Just2co  把这个换成你要检测的网站就行 https://github.com/jhao104/proxy_pool/blob/12cb7205b7518ea8a40447bdeb212f21c5f61397/Util/utilFunction.py#L100

**Comment by Just2co** [comment]
@jhao104 明白，真是太感谢你了，你这个项目还能让我学习到python编程，还能学习下怎么爬别人网上上IP跟端口

**Comment by Just2co** [comment]
@jhao104 直接 更换域名就行？每个网站不是有个请求get  网站header信息吗？要提前填进去检查是否匹配以确认代理IP是否可用的吧？

**Comment by jhao104** [comment]
@Just2co  有些网站不构造headers信息也是可以正常访问，你可以先不加代理测试下。 检测代理是否可用的话，直接的方法就是加上代理去访问网站，返回200状态码就是可用。
或者用代理访问这个网址 http://httpbin.org/ip 它会返回你访问的ip

**Comment by Just2co** [comment]
@jhao104 嗯，；了解了。你那边能帮忙把检测网站换成google.co.jp ，然后看看有没有可用IP，然后把IP跟端口贴上这里来，我这边弄成梯子的前置试一试！

**Comment by jhao104** [comment]
你直接改这里的代码就行啦
https://github.com/jhao104/proxy_pool/blob/12cb7205b7518ea8a40447bdeb212f21c5f61397/Util/utilFunction.py#L100
换成你要验证的网站
，而且你得抓国外代理才行

**Comment by jhao104** [comment]
你直接改这里的代码就行啦
https://github.com/jhao104/proxy_pool/blob/12cb7205b7518ea8a40447bdeb212f21c5f61397/Util/utilFunction.py#L100
换成你要验证的网站
，而且你得抓国外代理才行

**Comment by ChenYCL** [comment]
请问现在怎么配置呢，没有发现当前文件了

**Comment by jhao104** [comment]
> 请问现在怎么配置呢，没有发现当前文件了

现在移到了 `validator.py` https://github.com/jhao104/proxy_pool/blob/394072d49b34062d5a8ed1f1c60baa13fb98b59e/helper/validator.py#L58-L68
