### ISSUE TITLE
最新版本是否放弃对MongoDB的兼容

### ISSUE THREAD

**Issue by likenji** [jhao104/proxy_pool#410]
git clone 最新版本，
更改db_type变量为MongoDB，遇到错误提示，db_type不能为MongoDB.
请问这是新版本暂时没加载对MongoDB的兼容还是已经放弃对MongoDB的支持？

**Comment by jhao104** [comment]
mongodb没更新

> git clone 最新版本，
> 更改db_type变量为MongoDB，遇到错误提示，db_type不能为MongoDB.
> 请问这是新版本暂时没加载对MongoDB的兼容还是已经放弃对MongoDB的支持？

mongodb还没更新

**Comment by likenji** [comment]
> > git clone 最新版本，
> > 更改db_type变量为MongoDB，遇到错误提示，db_type不能为MongoDB.
> > 请问这是新版本暂时没加载对MongoDB的兼容还是已经放弃对MongoDB的支持？
> 
> mongodb还没更新

谢谢回复，了解。
