### ISSUE TITLE
py文件头注释 中的更新时间是自动生成的吗

### ISSUE THREAD

**Issue by forgeries** [jhao104/proxy_pool#415]
"""
-------------------------------------------------
   File Name：     WebRequest
   Description :   Network Requests Class
   Author :        J_hao
   date：          2017/7/31
-------------------------------------------------
   Change Activity:
                   2017/7/31:
-------------------------------------------------
"""

===》Change Activity:
手动改的还是什么插件自动生成的

**Comment by jhao104** [comment]
没有插件，手动改的
