### ISSUE TITLE
有验证代理是否可用的模块吗？

### ISSUE THREAD

**Issue by yuzhiyizhan** [jhao104/proxy_pool#433]
我找了一下没有看见验证代理是否可以用的模块

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/d4e5c76f652c7fdfd0d2232cfe078a479bf82ab9/Util/utilFunction.py#L79-L94

**Comment by yuzhiyizhan** [comment]
大佬,我觉得可以这样,把验证的url和headers给他弄到配置文件里去,比如我要爬的url需要特定的请求头,不然返回403,这时我只需要去修改配置文件的请求头就可以了，只是小小建议

**Comment by yuzhiyizhan** [comment]
已解决
