### ISSUE TITLE
its apear ..

### ISSUE THREAD

**Issue by rmros** [jhao104/proxy_pool#44]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. --->#  in browser

`ERROR:apscheduler.executors.default:Job "main (trigger: interval[0:05:00], next run at: 2017-06-14 23:20:31 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 73, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 42, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "../ProxyGetter/getFreeProxy.py", line 79, in freeProxySecond
    html = getHTMLText(url, headers=HEADER)
  File "../Util/utilFunction.py", line 31, in getHTMLText
    return response.status_code
UnboundLocalError: local variable 'response' referenced before assignment` --->#  in terminal

# how solve?

**Comment by jhao104** [comment]
are you success when you run this function(freeProxyFirst/freeProxySecond/freeProxyThird/freeProxyFourth/freeProxyFifth)  in `ProxyGetter/getFreeProxy.py`  alone;

i think you can't success some function

**Comment by rmros** [comment]
i checked proxyGetter.py file and i try to browse proxy sites in freeProxySecond freeProxyThird freeProxyFourth freeProxyFifth ,  some of them are very weak, and some of them have this message 

> This site can’t be reached

what i do?

**Comment by jhao104** [comment]
These are domestic websites. maybe you should use a Chinese VPN.
or change  another proxy site which you can access normal

**Comment by jackzhang8806** [comment]
Some functions in proxyGetter.py do not work properly. Second and third cannot open, it might lead to failed execution.

**Comment by rmros** [comment]
i have not chinese VPN , but what is your opinion if i delete 

> function(freeProxySecond/freeProxyThird/freeProxyFourth/freeProxyFifth)

 in ProxyGetter/getFreeProxy.py
else freeProxyFirst ?

**Comment by rmros** [comment]
@jackzhang8806   you have same problem?

**Comment by jhao104** [comment]
These functions you can customize.
The more proxy site there are, the more proxy there are
so i suggest change some proxy site which you can access

**Comment by rmros** [comment]
@jhao104  Thank you create this  :+1: 
can u give me your IM messanger id ?

**Comment by jhao104** [comment]
sy, only QQ or WeChat in china 😏

**Comment by rmros** [comment]
niaho jhao  :) 
i have QQ
what is your QQ?

**Comment by jackzhang8806** [comment]
@rmros  Yes, I got it, but I solve when I comment those two functions.
