### ISSUE TITLE
Docker 启动后python报错：无法连接到host.docker.internal

### ISSUE THREAD

**Issue by chariothy** [jhao104/proxy_pool#442]
报错：redis.exceptions.ConnectionError: Error -2 connecting to host.docker.internal:6379. Name or service not known.
docker命令：docker run --env db_type=REDIS --env db_host=host.docker.internal --env db_port=6379 -p 5010:5010 jhao104/proxy_pool
Redis安装在本机，监听端口：0.0.0.0:6379 
Redis-cli可以成功连接。

**Comment by jhao104** [comment]
参考 https://github.com/jhao104/proxy_pool/issues/434

**Comment by chariothy** [comment]
这个看过的，我跟他不一样，他用的是127.0.0.1，在容器中肯定是不能用这个地址来访问宿主机的，而我已经用的是host.docker.internal这个地址了。

**Comment by YumeMichi** [comment]
> 这个看过的，我跟他不一样，他用的是127.0.0.1，在容器中肯定是不能用这个地址来访问宿主机的，而我已经用的是host.docker.internal这个地址了。

我查了一下host.docker.internal这东西好像只有Docker for Mac有？你确定这个能解析出来吗

**Comment by chariothy** [comment]
> > 这个看过的，我跟他不一样，他用的是127.0.0.1，在容器中肯定是不能用这个地址来访问宿主机的，而我已经用的是host.docker.internal这个地址了。
> 
> 我查了一下host.docker.internal这东西好像只有Docker for Mac有？你确定这个能解析出来吗？
> 你的报错`Name or service not known.` 本来就是解析不了

docker 18.03 中加入了的这个 feature，在容器中可以通过 host.docker.internal来访问主机。不仅仅是docker for mac。我的docker版本是19.03.8 。
如果不支持的话，为啥要在README中加入这个用法呢？

**Comment by jhao104** [comment]
@chariothy 我这边也是用19版本的docker使用`host.docker.internal`是没问题的，如果不行还可以使用host网络模式，参考  https://github.com/jhao104/proxy_pool/issues/434

**Comment by chariothy** [comment]
用host网络模式问题已解决，谢谢！
