### ISSUE TITLE
useful队列内的代理怎么验证可用性？

### ISSUE THREAD

**Issue by WenyuLei** [jhao104/proxy_pool#46]
比如10min之前（或者更久）塞了一批验证通过的代理放到useful队列中，过了10min某个代理被spider取出来使用，这个时候这个proxy不一定可用吧

**Comment by WenyuLei** [comment]
有没有进程定期去清理useful队列内的代理呢

**Comment by jhao104** [comment]
看文档吧。 ProxyRefreshSchedule.py定时验证useful
