### ISSUE TITLE
我发现在运行一段时间后(2天多点), 就不再爬取新代理了

### ISSUE THREAD

**Issue by Singloo** [jhao104/proxy_pool#466]
每次都是start之后立马exit
这是因为ip被代理网站屏蔽了吗?

**Comment by Singloo** [comment]
然后需要重启container, 重启之后又可以正常使用了

**Comment by jhao104** [comment]
报什么错，有日志吗

**Comment by Singloo** [comment]
> 报什么错，有日志吗

```
2020-06-26 21:19:50,322 base.py[line:917] DEBUG Looking for jobs to run
2020-06-26 21:19:50,322 base.py[line:943] WARNING Execution of job "raw_proxy定时采集 (trigger: interval[0:05:00], next run at: 2020-06-26 21:19:50 CST)" skipped: maximum number of running instances reached (1)
2020-06-26 21:19:50,323 base.py[line:985] DEBUG Next wakeup is due at 2020-06-26 21:20:50.321214+08:00 (in 59.998663 seconds)
```

现在就是只检查proxy,不爬取新的proxy了

**Comment by Singloo** [comment]
目前的解决方案是, 给 `rawProxyScheduler` 加了个timeout

**Comment by jhao104** [comment]
> > 报什么错，有日志吗
> 
> ```
> 2020-06-26 21:19:50,322 base.py[line:917] DEBUG Looking for jobs to run
> 2020-06-26 21:19:50,322 base.py[line:943] WARNING Execution of job "raw_proxy定时采集 (trigger: interval[0:05:00], next run at: 2020-06-26 21:19:50 CST)" skipped: maximum number of running instances reached (1)
> 2020-06-26 21:19:50,323 base.py[line:985] DEBUG Next wakeup is due at 2020-06-26 21:20:50.321214+08:00 (in 59.998663 seconds)
> ```
> 
> 现在就是只检查proxy,不爬取新的proxy了

这是采集运行时间超过了interval，一般采集用不到好久，应该是有些代理网站不能用了，

**Comment by Singloo** [comment]
> > > 报什么错，有日志吗
> > 
> > 
> > ```
> > 2020-06-26 21:19:50,322 base.py[line:917] DEBUG Looking for jobs to run
> > 2020-06-26 21:19:50,322 base.py[line:943] WARNING Execution of job "raw_proxy定时采集 (trigger: interval[0:05:00], next run at: 2020-06-26 21:19:50 CST)" skipped: maximum number of running instances reached (1)
> > 2020-06-26 21:19:50,323 base.py[line:985] DEBUG Next wakeup is due at 2020-06-26 21:20:50.321214+08:00 (in 59.998663 seconds)
> > ```
> > 
> > 
> > 现在就是只检查proxy,不爬取新的proxy了
> 
> 这是采集运行时间超过了interval，一般采集用不到好久，应该是有些代理网站不能用了，

好的, 还有个问题, 我现在用两台服务器跑, 共享一个redis, 这样效率会更高吗? 还是一样? 我的爬虫对代理需求量比较大

**Comment by jhao104** [comment]
要采集的代理源够充足才行

**Comment by Singloo** [comment]
Thanks♪(･ω･)ﾉ
