### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by yilu1015** [jhao104/proxy_pool#471]
没有用Docker，安装了`requirements.txt`里的依赖，更新了`setting.py`中Redis的地址，但启动`python proxyPool.py schedule`时提示：

```
  File "proxyPool.py", line 17, in <module>
    from config.setting import BANNER
ModuleNotFoundError: No module named 'config'
```
问题出在哪里了呢？

**Comment by StarkShang** [comment]
遇到了同样的问题，使用docker也有同样的问题

> Traceback (most recent call last):
>  File "proxyPool.py", line 17, in <module>
>    from config.setting import BANNER
> ModuleNotFoundError: No module named 'config'

**Comment by StarkShang** [comment]
应该是文件结构进行修改后这里没有修改

proxyPool.py第17行改为from setting就行 #472

**Comment by yilu1015** [comment]
谢谢。就是这个问题，已解决！
