### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by bebestmaple** [jhao104/proxy_pool#489]
docker启动报如下错误
 Traceback (most recent call last):                                                                                                                                                            │
│     File "proxyPool.py", line 18, in <module>                                                                                                                                                   │
│       from helper.scheduler import runScheduler                                                                                                                                                 │
│     File "/app/helper/scheduler.py", line 19, in <module>                                                                                                                                       │
│       from helper.fetch import runFetcher                                                                                                                                                       │
│     File "/app/helper/fetch.py", line 15, in <module>                                                                                                                                           │
│       from handler.logHandler import LogHandler                                                                                                                                                 │
│     File "/app/handler/logHandler.py", line 38, in <module>                                                                                                                                     │
│       os.mkdir(LOG_PATH)                                                                                                                                                                        │
│   FileExistsError: [Errno 17] File exists: '/app/handler/../log'

**Comment by jhao104** [comment]
```
haosMBP:Demo jhao$ docker pull jhao104/proxy_pool:2.1.0
2.1.0: Pulling from jhao104/proxy_pool
df20fa9351a1: Already exists
36b3adc4ff6f: Already exists
98eb400f742f: Already exists
31cc876ef68f: Already exists
e8928b84e39a: Already exists
8f7be8aad01d: Already exists
e1d92897ed1b: Already exists
d0438fe81a42: Already exists
0b442e9e310a: Already exists
90017b7f296f: Already exists
Digest: sha256:1af4f0a7f9fadfb1ec48e992af910f4bf45264c64d55c2850f2a805da0ba2542
Status: Downloaded newer image for jhao104/proxy_pool:2.1.0
jhaosMBP:Demo jhao$ docker run --env DB_CONN=redis://:pwd@*.*.*.*:6379/0 -p 5010:5010 jhao104/proxy_pool:2.1.0

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************


****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2020-07-24 01:45:26,901 fetch.py[line:35] INFO ProxyFetch : start
2020-07-24 01:45:26,902 fetch.py[line:37] INFO ProxyFetch - freeProxy01: start
[2020-07-24 01:45:26 +0000] [9] [INFO] Starting gunicorn 19.9.0
[2020-07-24 01:45:26 +0000] [9] [INFO] Listening at: http://0.0.0.0:5010 (9)
[2020-07-24 01:45:26 +0000] [9] [INFO] Using worker: sync
[2020-07-24 01:45:26 +0000] [21] [INFO] Booting worker with pid: 21
[2020-07-24 01:45:27 +0000] [22] [INFO] Booting worker with pid: 22
[2020-07-24 01:45:27 +0000] [23] [INFO] Booting worker with pid: 23
2020-07-24 01:45:27,123 fetch.py[line:52] INFO ProxyFetch - freeProxy01: 60.179.201.207:3000     success
2020-07-24 01:45:27,123 fetch.py[line:52] INFO ProxyFetch - freeProxy01: 60.179.200.202:3000     success
2020-07-24 01:45:27,124 fetch.py[line:52] INFO ProxyFetch - freeProxy01: 60.184.110.80:3000      success
```

我这边测试最新版本2.1.0是没问题的

**Comment by bebestmaple** [comment]
我也是最新的lastest版本

**Comment by jhao104** [comment]
用release 2.1.0------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;bebestmaple&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月24日(星期五) 下午3:29
收件人:&nbsp;&quot;jhao104/proxy_pool&quot;<proxy_pool@noreply.github.com&gt;;
抄送:&nbsp;&quot;J_hao104&quot;<946150454@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jhao104/proxy_pool] docker启动报错 (#489)

**Comment by bebestmaple** [comment]
好的  我试试  感谢

**Comment by bebestmaple** [comment]
2.1.0正常  lastest启动失败
