### ISSUE TITLE
为何必须要先运行redis?

### ISSUE THREAD

**Issue by kxltsuper** [jhao104/proxy_pool#49]
你好jhao104，我看文档说是用SSDB来替代redis，但实际运行程序中，如果不先运行redis就运行main.py，就会报错，新手请指教，谢谢。(windows 8 64位系统)。而且有时运行成功，但没有任何代理显示出来，在浏览器中只是可怜的显示[ ]。

**Comment by jhao104** [comment]
你配置 配的是SSDB么

**Comment by kxltsuper** [comment]
是不是这个爬虫程序要运行在Linux下才行？

**Comment by jhao104** [comment]
不是, 看你的配置和py版本 配置SSDB就不会有你上面说的问题

**Comment by thisforeda** [comment]
redis 有 Windows 版本。
参见这里 https://github.com/MicrosoftArchive/redis/releases

**Comment by alexanderhawl** [comment]
linux 用redis的话，需要在Config.ini中，把port=8888注释掉，然后把port=6379取消注释吗？楼主，在readme.md中没有看到这个

**Comment by jhao104** [comment]
@alexanderhawl redis和ssdb一样的配置 端口配置正确就行

**Comment by jhao104** [comment]
@pblh123 redis命令行啊 或者找个redis可视化工具

**Comment by pblh123** [comment]
我不会用redis，还在学。如果有相关教程就好了

**Comment by hhaoao** [comment]
@jhao104  我也遇到这问题，我用的是ssdb数据库而且能正常访问，但定时任务全挂了，就是定时校正proxy，定时爬取proxy都失灵了，只能手动杀掉进程，重启main.py，因为我是按照这里写进windows服务里[#112](https://github.com/jhao104/proxy_pool/issues/112)，数据库也是开机启动，谁先启动，这个我也不太清楚，看到网上说可以改注册表来设置启动顺序，但这注册表真心不想动呀。目前我用延时启动暂时解决这个问题，不知道大佬有没有更好的方式，或者弄个检测数据库是否启动的函数?
下面是我发现有问题后做的小测试，先将main.py启动后再去启动数据库的结果，报错是11061。
![default](https://user-images.githubusercontent.com/11269610/44149793-e3781db8-a0cf-11e8-9151-a83115c5f19b.png)

![default](https://user-images.githubusercontent.com/11269610/44149746-bee77bf6-a0cf-11e8-8776-e3055ac1c0bf.png)
