### ISSUE TITLE
is proxy pool double ip checker?

### ISSUE THREAD

**Issue by rmros** [jhao104/proxy_pool#51]
my mean
if we give same ip:port from several sources

example :
192.168.56.1:123 from X
and
192.168.56.1:123 from Y

jhao proxy_pool can resolve this?

**Comment by jhao104** [comment]
当然行，用hash结构存的代理

**Comment by rmros** [comment]
@jhao104  meaning of course sure
this used hash structure

meanning yes?

**Comment by jhao104** [comment]
exactly

**Comment by rmros** [comment]
@jhao104  wow my Chinese is well
closed issue
xie xie
