### ISSUE TITLE
SSDB可视化配置问题

### ISSUE THREAD

**Issue by Macintoshxz** [jhao104/proxy_pool#52]
请教， 在分别运行Api下的ProxyApi.py,  Schedule下的ProxyRefreshSchedule.py和ProxyValidSchedule.py后，  想通过README里提供的SSDBAdmin可视化工具查看结果，请问SSDBAdmin的 setting.py 中的‘host’和‘port’如何设置？  

#!/usr/bin/env python

servers = [
    {
        "host": "172.16.1.69",
        "port": 8889
    },
    {
        "host": "127.0.0.1",
        "port": 8889
    }
]
   
DEBUG = False
### 补充： 
在运行ProxyApi.py,ProxyRefreshSchedule.py和ProxyValidSchedule.py时， 运行SSDBAdmin下的 runserver.py出现了socket占用错误：socket.error: [Errno 98] Address already in use.  由于在此之前没有redis和其他数据库经验，请多指教， 谢谢！

**Comment by jhao104** [comment]
host和port就是你SSDB数据库对应的ip和端口，配一个，删掉多余的一个就行。

端口被占用应该是server的5000端口被占用了，如果不是你其他程序占用的话，就ps看进程，可能是你之前已经起过，没有杀掉

**Comment by Macintoshxz** [comment]
fixed

**Comment by Macintoshxz** [comment]
初学者的问题：
把解决过程写下来，避免重复发生

数据库用的是SSDB， 出现socket.error: [Errno 98] Address already in use 是因为SSDBAdmin可视化工具默认端口和ProxyApi.py端口冲突了：

1. 需要把ProxyApi端口改一下
2. 可视化工具的ip和端口需要与SSDB的ip和端口一致
3. proxy_pool的数据库的配置要与SSDB的ip和端口一致

运行程序后，打开可视化工具，在hash标签下可以看到‘raw_proxy’，‘useful_proxy’两个列表， ‘useful_proxy’里是经过验证的可用proxy。
