### ISSUE TITLE
请问一下为什么好久都获取不到proxy

### ISSUE THREAD

**Issue by Linkeer365** [jhao104/proxy_pool#520]
[my settings.py](https://paste.ubuntu.com/p/Vw4pGMnHGQ/)

[webserver's running log](https://paste.ubuntu.com/p/pXycpGmC7q/)

> _http://127.0.0.1:5010/get_all/_
->  []

> http://127.0.0.1:5010/get/
-> {"code":0,"src":"no proxy"}

多谢！

**Comment by freedomlyle** [comment]
跟你问题一样，我也想求解答

**Comment by freedomlyle** [comment]
先用python proxyPool.py schedule命令拿点地址，等一会关了，再用python proxyPool.py server
