### ISSUE TITLE
kuaidaili标签变更

### ISSUE THREAD

**Issue by shaoxyz** [jhao104/proxy_pool#53]
应为tree.xpath(//*[@id="freelist"]/table/tbody/tr)

**Comment by jhao104** [comment]
快代理应该拿不到代理数据了吧，他前端用js做了cookie加密

**Comment by Shaw-lib** [comment]
刚刚试了下，可以的，
header={
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.8',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
}

**Comment by jhao104** [comment]
已更新 26ece72727cb17c77941e0dbb9708084df570dfb
