### ISSUE TITLE
编译 lxml 服务器直接卡死  Building wheel for lxml (setup.py): started

### ISSUE THREAD

**Issue by MQL9011** [jhao104/proxy_pool#537]
用docker跑的
cd 到项目
docker-compose up -d
然后服务器就卡死了

**Comment by Michaelsky0913** [comment]
服务器卡死是你机器性能不够吧

**Comment by MQL9011** [comment]
@Michaelsky0913   是的....学生机内存不够.....要是能照顾下这种小破服务器就好了

**Comment by jhao104** [comment]
小服务器就别用docker了，直接跑项目就行了。我这个的demo服务加数据库都是放在一台小服务器上直接跑的，没啥问题
