### ISSUE TITLE
Please update werkzeug to 0.15.5

### ISSUE THREAD

**Issue by cw760** [jhao104/proxy_pool#546]
When I run ```python proxyPool.py server```, I get the error like below:
```
TypeError: required field "type_ignores" missing from Module
```
Mac OS   Big Sur   
Python 3.8

Update werkzeug to 0.15.5 can fix it.

**Comment by Unknown-Chinese-User** [comment]
run `pip install --upgrade werkzeug` in shell can fix it

**Comment by cw760** [comment]
Update werkzeug to 0.15.5 can fix it.
