### ISSUE TITLE
新手求教，如何把API地址投到公网

### ISSUE THREAD

**Issue by TophTab** [jhao104/proxy_pool#547]
首先我的环境是阿里云的centos7，通过docker 运行jhao104/proxy_pool
我修改容器内setting.py中API的host，但是无法投到公网上
想知道各位前辈是然后投到公网上的
谢谢各位前辈了

谢谢各位前辈，已经搞定了。

**Comment by catfishlty** [comment]
### 方法
1. 配置Nginx，指定域名和端口并路由到proxy_pool的端口
2. 阿里云配置开放端口（Nginx端口）

### 特别注意
公网无访问校验的端口有大概率被扫出来恶意使用，注意服务器安全措施

**Comment by YumeMichi** [comment]
直接按照readme的docker语句运行容器 访问公网IP:5010就行了（防火墙记得开放相应端口 系统中的防火墙 以及 云平台的防火墙
