### ISSUE TITLE
Error 10061 connecting localhost:8888

### ISSUE THREAD

**Issue by wxw663** [jhao104/proxy_pool#55]
你好，我在配置完依赖环境后跑了main.py然后就返回了ConnectionError: Error 10061 connecting localhost:8888 我还是新手没接触过SSDB方面的东西，不知道是不是我SSDB的配置有问题？单独运行getFreeProxy是可以返回IP列表的，应该就是数据库设置有问题吧，我把它放到云服务器上用SSDBAdmin改了服务器公网IP访问也还是返回10061的错误，请问我是还需要设置什么？谢谢。

**Comment by jhao104** [comment]
@wxw663 你的SSDB服务启起来了吗？端口是配的8888吗

**Comment by wxw663** [comment]
是我的问题我以为python里的ssdb模块就是数据库了。。。装了SSDB以后运行起来就好了。真是抱歉我犯这么低级的错误还不自知。。。
