### ISSUE TITLE
关于pycharm里的No module named 'chardet.version' 

### ISSUE THREAD

**Issue by YuSekai** [jhao104/proxy_pool#551]
在pycharm里跑了一下显示
 from .version import __version__, VERSION
ModuleNotFoundError: No module named 'chardet.version'

找了一下发现是因为proxyPool.py里 
from setting import BANNER, VERSION没有起作用
加个.就好了
from .setting import BANNER, VERSION

**Comment by YuSekai** [comment]
> 在pycharm里跑了一下显示
> from .version import **version**, VERSION
> ModuleNotFoundError: No module named 'chardet.version'
> 
> 找了一下发现是因为proxyPool.py里
> from setting import BANNER, VERSION没有起作用
> 加个.就好了
> from .setting import BANNER, VERSION

....后来发现还是有一样的问题因为 proxyPool.py和setting.py没有设置好根目录 
于是在proxyPool.py里加上

import os
miport sys
sys.path.append(os.getcwd())

就行了……

**Comment by jhao104** [comment]
需要在pycharm里面设置将当前项目路径加入python搜索路径就行了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月23日(星期二) 下午4:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [jhao104/proxy_pool] 关于pycharm里的No module named &#39;chardet.version&#39;  (#551)
