### ISSUE TITLE
请求分类

### ISSUE THREAD

**Issue by oklqh** [jhao104/proxy_pool#56]
不知道可不可以在get的时候，指定https或者http型代理，毕竟有些代理只支持http或者https？

谢谢！

**Comment by oklqh** [comment]
类似这样：
127.0.0.1:5000/get/?type=http
127.0.0.1:5000/get/?type=https

我没细看代码，难道每个ip都通过百度做了验证？

**Comment by jhao104** [comment]
@oklqh 是的。这个确实是个改进点。列在计划中

**Comment by lenlin** [comment]
类型可以增加显示出IP地址是哪里的，响应验证地址的时间多少。

**Comment by jhao104** [comment]
已更新
