### ISSUE TITLE
西刺被Ban

### ISSUE THREAD

**Issue by carrie0307** [jhao104/proxy_pool#57]
你好，自己在写一个类似的练习，但抓取西刺代理时就出现多次被Ban所得页面是block的情况，请问您是通过不断更换headers处理还是怎样呢？

新手求教，谢谢大神！

**Comment by jhao104** [comment]
这个项目里面频率比较低，每个10分钟抓一次，一次只抓前5页。 其实都不用前5页。10分钟最多更新一页。时间太久的IP基本没用，没必要抓

**Comment by carrie0307** [comment]
好的谢谢，我再尝试一下
