### ISSUE TITLE
代理验活机制存在问题

### ISSUE THREAD

**Issue by LztCode** [jhao104/proxy_pool#572]
两次验活时间差有一个小时之多，希望作者能够改进下

**Comment by jhao104** [comment]
check默认是两分钟一次，你可以调demo接口看last_time字段

**Comment by LztCode** [comment]
> check默认是两分钟一次，你可以调demo接口看last_time字段

我在last_time字段里面看到相差近1小时，调用all接口看，我在本地服务器搭建的，我配置的代理验证时超时时间是3秒，会不会跟这个有关

**Comment by LztCode** [comment]
> check默认是两分钟一次，你可以调demo接口看last_time字段

![image](https://user-images.githubusercontent.com/73683679/120159993-5e35da00-c228-11eb-9329-75b61aadd3ff.png)

**Comment by jhao104** [comment]
@LztCode  
1、检查下UseProxyCheck有没有报错；
2、代码是否是最新

我这边看我demo服务所有代理last_time都是近一分钟的，刚才我在本地又跑了一次大约半个小时，未发现你这个问题。

**Comment by LztCode** [comment]
> @LztCode
> 1、检查下UseProxyCheck有没有报错；
> 2、代码是否是最新
> 
> 我这边看我demo服务所有代理last_time都是近一分钟的，刚才我在本地又跑了一次大约半个小时，未发现你这个问题。
> 另外把你的猫关了

代码是最新的，前两天才clone，我是在本地的一台大型服务器上跑的，这是我本机的猫应该没啥联系，我从不开全局代理。
在输出那里看到_RawProxyCheck_验活大片大片都是fail，是不是设置的超时时间过短，导致验活失败，没更新到数据库
![image](https://user-images.githubusercontent.com/73683679/120170214-529be080-c233-11eb-840f-36265c56d55e.png)

**Comment by jhao104** [comment]
> > @LztCode
> > 1、检查下UseProxyCheck有没有报错；
> > 2、代码是否是最新
> > 我这边看我demo服务所有代理last_time都是近一分钟的，刚才我在本地又跑了一次大约半个小时，未发现你这个问题。
> > 另外把你的猫关了
> 
> 代码是最新的，前两天才clone，我是在本地的一台大型服务器上跑的，这是我本机的猫应该没啥联系，我从不开全局代理。
> 在输出那里看到_RawProxyCheck_验活大片大片都是fail，是不是设置的超时时间过短，导致验活失败，没更新到数据库
> ![image](https://user-images.githubusercontent.com/73683679/120170214-529be080-c233-11eb-840f-36265c56d55e.png)

验活返回的fail会delete掉redis中的proxy, 每次验证都是getall验证后update、delete。
你可以把数据库历史数据清掉， 开一个任务重跑在控制台观察下

**Comment by jhao104** [comment]
![image](https://user-images.githubusercontent.com/15058920/120171510-b2df5200-c234-11eb-9d1a-12da9769c9c8.png)
我这边在本地启了个服务，last_time是在验证隔间的两分钟之内

**Comment by LztCode** [comment]
> ![image](https://user-images.githubusercontent.com/15058920/120171510-b2df5200-c234-11eb-9d1a-12da9769c9c8.png)
> 我这边在本地启了个服务，last_time是在验证隔间的两分钟之内

快下班了，先跑一晚上，明天再看看结果

**Comment by LztCode** [comment]
> ![image](https://user-images.githubusercontent.com/15058920/120171510-b2df5200-c234-11eb-9d1a-12da9769c9c8.png)
> 我这边在本地启了个服务，last_time是在验证隔间的两分钟之内

我又复现了这个问题，当验活超时设置成1秒，爬取触发为40的时候就出现这个问题，我猜是没来得及验活便触发爬取

**Comment by jhao104** [comment]
@LztCode 我这边找到问题所在了
原来验活逻辑:
https://github.com/jhao104/proxy_pool/blob/b8cc27d3f42d2c5e5445e7a4f8f1654eaece6bc3/helper/scheduler.py#L37-L45

在验证比较苛刻的情况下池子里面的代理数量一直小于poolSizeMin, 就只运行采集而没有验证。

可以改成:
```python
def __runProxyCheck():
    proxy_handler = ProxyHandler()
    proxy_queue = Queue()
    if proxy_handler.db.getCount().get("total", 0) < proxy_handler.conf.poolSizeMin:
        __runProxyFetch()
    for proxy in proxy_handler.getAll():
        proxy_queue.put(proxy)
    Checker("use", proxy_queue)
```
