### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Monster-DP** [jhao104/proxy_pool#579]
![image](https://user-images.githubusercontent.com/47738288/122666462-f0098500-d1df-11eb-9cc9-4018fdddab9f.png)

**Comment by jhao104** [comment]
日志很清楚了，连不上127.0.0.1 6379这个库

**Comment by Monster-DP** [comment]
可是我不知道该怎么办
![image](https://user-images.githubusercontent.com/47738288/122729156-6f17bf80-d2ab-11eb-8177-dc61275e843d.png)

**Comment by Createitv** [comment]
> 日志很清楚了，连不上127.0.0.1 6379这个库
`DB_CONN = 'redis://:pwd@127.0.0.1:8888/0'` pwd有就填自己密码没有就删除

**Comment by Monster-DP** [comment]
我安装了 redis 然后删除了密码 可以了  爱你哟！

**Comment by Monster-DP** [comment]
能成功启动调度程序 
![image](https://user-images.githubusercontent.com/47738288/122939378-255fcf80-d3a6-11eb-8715-7728254a19cf.png)
![image](https://user-images.githubusercontent.com/47738288/122939412-2db80a80-d3a6-11eb-9859-06b102f459a2.png)
但是无法启动api服务
![image](https://user-images.githubusercontent.com/47738288/122939544-4b856f80-d3a6-11eb-9890-5a5e612a734a.png)

**Comment by Createitv** [comment]
> 能成功启动调度程序
> ![image](https://user-images.githubusercontent.com/47738288/122939378-255fcf80-d3a6-11eb-8715-7728254a19cf.png)
> ![image](https://user-images.githubusercontent.com/47738288/122939412-2db80a80-d3a6-11eb-9859-06b102f459a2.png)
> 但是无法启动api服务
> ![image](https://user-images.githubusercontent.com/47738288/122939544-4b856f80-d3a6-11eb-9890-5a5e612a734a.png)

要把ProxyPool 0.0.0.0改为127.0.0.1本地访问，然后加上端口号在本地浏览器访问例如`127.0.0.1:5010/get`

**Comment by Monster-DP** [comment]
0.0.0.0改为127.0.0.1还是报错![image](https://user-images.githubusercontent.com/47738288/123013931-be6b0680-d3f7-11eb-9900-5562f1f7d5c6.png)

![image](https://user-images.githubusercontent.com/47738288/123013637-2836e080-d3f7-11eb-93d6-1b86630a734a.png)
![image](https://user-images.githubusercontent.com/47738288/123013997-df335c00-d3f7-11eb-816e-878f2e743ff2.png)

**Comment by jhao104** [comment]
包的问题, 最好使用文档里面说明的支持的版本。
看下 https://www.jianshu.com/p/95588bf4e63d?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation

**Comment by Monster-DP** [comment]
成功解决 谢谢大佬！！十分感谢！！
