### ISSUE TITLE
这个验活机制不是很合理

### ISSUE THREAD

**Issue by LztCode** [jhao104/proxy_pool#580]
验活不应该只看**响应码**，应该检索一些验活目标(qq.com)的特征，比如说ico，特定的元素，有些代理是返回一些他自身服务器的垃圾页面，比如说欠费、报错什么的
尽可能提高质量的情况下可以牺牲一些速度，不是吗？

**Comment by jhao104** [comment]
提供了自定义的功能 可以自己加或者改

**Comment by LztCode** [comment]
这不应该是代理池验活标配吗，对了，在哪里有自定义功能？给个文档来看下，我有空去改改

**Comment by jhao104** [comment]
如果你需要的话麻烦你仔细看文档哈

**Comment by LztCode** [comment]
> 如果你需要的话麻烦你仔细看文档哈，文档地址在readme开头有给

![image](https://user-images.githubusercontent.com/73683679/122738030-329c9180-d2b4-11eb-8c7b-87db8797c0e7.png)
大佬快帮忙看看我这个写得对不对劲，需不需要考虑http和https两种情况

**Comment by jhao104** [comment]
> > 如果你需要的话麻烦你仔细看文档哈，文档地址在readme开头有给
> 
> ![image](https://user-images.githubusercontent.com/73683679/122738030-329c9180-d2b4-11eb-8c7b-87db8797c0e7.png)
> 大佬快帮忙看看我这个写得对不对劲，需不需要考虑http和https两种情况

httpValidator验证方法返回True就代表代理可用然后调用httpsValidator, 后者返回True就代表支持https。

如果你需要全都支持https就在httpValidator里面把你想验证的全做了，删掉httpsValidator

**Comment by LztCode** [comment]
> > > 如果你需要的话麻烦你仔细看文档哈，文档地址在readme开头有给
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/73683679/122738030-329c9180-d2b4-11eb-8c7b-87db8797c0e7.png)
> > 大佬快帮忙看看我这个写得对不对劲，需不需要考虑http和https两种情况
> 
> httpValidator验证方法返回True就代表代理可用然后调用httpsValidator, 后者返回True就代表支持https。
> 
> 如果你需要全都支持https就在httpValidator里面把你想验证的全做了，删掉httpsValidator

那这三者的调用顺序是怎么样的？我只需要http通过就行了

**Comment by jhao104** [comment]
这部分文档里面也有讲。
 > 代理校验方法分为三类: preValidator 、 httpValidator 、 httpsValidator：
>  preValidator: 预校验，在代理抓取后验证前调用，目前实现了 formatValidator 校验代理IP格式是否合法；
>  httpValidator: 代理可用性校验，通过则认为代理可用， 目前实现了 httpTimeOutValidator 校验；
>  httpsValidator: 校验代理是否支持https，目前实现了 httpsTimeOutValidator 校验。

http通过代理就会入池了, https通过就会打上https的属性

**Comment by LztCode** [comment]
> 这部分文档里面也有讲。
> 
> > 代理校验方法分为三类: preValidator 、 httpValidator 、 httpsValidator：
> > preValidator: 预校验，在代理抓取后验证前调用，目前实现了 formatValidator 校验代理IP格式是否合法；
> > httpValidator: 代理可用性校验，通过则认为代理可用， 目前实现了 httpTimeOutValidator 校验；
> > httpsValidator: 校验代理是否支持https，目前实现了 httpsTimeOutValidator 校验。
> 
> http通过代理就会入池了, https通过就会打上https的属性

okok
