### ISSUE TITLE
最新的docker没法pull

### ISSUE THREAD

**Issue by dfmjndm** [jhao104/proxy_pool#587]
https://github.com/jhao104/proxy_pool/packages/706076这个地址的docker没法pull下来
README.md里面的docker run --env DB_CONN=redis://:password@ip:port/db -p 5010:5010 jhao104/proxy_pool:latest也无法运行

**Comment by jhao104** [comment]
没有pull是网络问题吗？
可以试试用dockerhub的镜像: docker pull jhao104/proxy_pool

无法运行的话贴下报错

**Comment by dfmjndm** [comment]
好吧，是网络问题，dockerhub的可以pull了
