### ISSUE TITLE
docker 启动容器报错

### ISSUE THREAD

**Issue by L-GROSS** [jhao104/proxy_pool#611]
redis.exceptions.ResponseError: value is not an integer or out of range
2021-11-18 13:18:50,699 launcher.py[line:39] INFO exit!
2021-11-18 13:18:50,692 redisClient.py[line:152] ERROR redis connection error: value is not an integer or out of range

**Comment by YumeMichi** [comment]
啥启动命令

**Comment by jhao104** [comment]
> redis.exceptions.ResponseError: value is not an integer or out of range 2021-11-18 13:18:50,699 launcher.py[line:39] INFO exit! 2021-11-18 13:18:50,692 redisClient.py[line:152] ERROR redis connection error: value is not an integer or out of range

redis地址配置问题 。 `redis://:password@ip:port/db` 这里的db是redis数据库 是0到15的数字

**Comment by L-GROSS** [comment]
密码为空咋办呢

**Comment by L-GROSS** [comment]
docker run --env DB_CONN=redis://:@192.168.56.107:6379/db5 -p 8899:5010 jhao104/proxy_pool:latest

**Comment by L-GROSS** [comment]
docker run --env DB_CONN=redis://:@192.168.56.107:6379/db11 -p 8899:5010 jhao104/proxy_pool:latest

redis.exceptions.ResponseError: value is not an integer or out of range

**Comment by jhao104** [comment]
> docker run --env DB_CONN=redis://:@192.168.56.107:6379/db11 -p 8899:5010 jhao104/proxy_pool:latest
> 
> redis.exceptions.ResponseError: value is not an integer or out of range

11的话库就是 db就是11
看一下文档: https://proxy-pool.readthedocs.io/zh/latest/user/how_to_config.html#id2

**Comment by L-GROSS** [comment]
OK  感谢

**Comment by L-GROSS** [comment]
大佬，咋验证   代理有效的啊
