### ISSUE TITLE
arm架构机器上使用docker启动报错

### ISSUE THREAD

**Issue by ljgjjb** [jhao104/proxy_pool#613]
在arm64机器上使用docker启动是报错The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
请问后续docker会支持到arm架构吗

**Comment by jhao104** [comment]
你可以自己用代码打一个镜像

**Comment by ljgjjb** [comment]
没有做过镜像，可以指点下关键词吗，我好去搜索
