### ISSUE TITLE
关于ProxyRefreshSchedule里的validProxy方法的疑问

### ISSUE THREAD

**Issue by wang-ye** [jhao104/proxy_pool#62]
hi，
在https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py#L51

这里exist_proxy没有看懂：

self.db.changeTable(self.raw_proxy_queue)
raw_proxy = self.db.pop()
self.log.info('%s start validProxy_a' % time.ctime())
exist_proxy = self.db.getAll()

这里exist_proxy是不是应该从useful_proxy_queue读取呢？

**Comment by jhao104** [comment]
整个有两处验证，一个是验证刚抓取的代理raw_proxy, 还有个是验证之前验证过后的代理
你说的应该是这个 https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyValidSchedule.py#L29

仔细看这里分别运行了两种验证：
https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py#L73

**Comment by wang-ye** [comment]
还是有点不太明白。https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py#L53
我的真正问题是在什么情况下，raw_proxy not in exist_proxy 是True呢？ 我觉得这个始终是False

**Comment by wang-ye** [comment]
明白了谢谢！
