### ISSUE TITLE
关于ProxyValidSchedule里的计数问题

### ISSUE THREAD

**Issue by wang-ye** [jhao104/proxy_pool#63]
在ProxyValidSchedule中，如果一个proxy存在很长时间，那么即使失效，它的计数也会很大，需要很久才能减为负数并被清理掉。如果设置一个计数的上限，比如10。当计数超过十就不再增加，是不是可以更有效地清理过期的proxy？

**Comment by jhao104** [comment]
@wang-ye 以扩展这个功能，感谢建议
