### ISSUE TITLE
启动后直接结束了，有大佬知道咋回事吗

### ISSUE THREAD

**Issue by harrydl** [jhao104/proxy_pool#648]
![image](https://user-images.githubusercontent.com/81464730/158110518-f8827127-ceb8-4e68-b6a9-dcaf30224508.png)
启动后出现这个就结束了

**Comment by harrydl** [comment]
![image](https://user-images.githubusercontent.com/81464730/158110753-7ff0ad6b-66e9-4d60-a9fd-f227b65cc96e.png)

**Comment by jhao104** [comment]
看下文档
```
# 如果已经具备运行条件, 可用通过proxyPool.py启动。
# 程序分为: schedule 调度程序 和 server Api服务

# 启动调度程序
python proxyPool.py schedule

# 启动webApi服务
python proxyPool.py server
```
