### ISSUE TITLE
docker启动连接redis出错

### ISSUE THREAD

**Issue by Honee-W** [jhao104/proxy_pool#649]
redis-server是在WSL上运行的。
ip分别使用了0.0.0.0和127.0.0.1
docker run --env DB_CONN=redis://:密码@0.0.0.0:6379/0 -p 5010:5010 jhao104/proxy_pool:2.4.0
docker run --env DB_CONN=redis://:密码@127.0.0.1:6379/0 -p 5010:5010 jhao104/proxy_pool:2.4.0
报错：
redis.exceptions.ConnectionError: Error 111 connecting to ip:6379. Connection refused.

不知道哪里出了问题，麻烦懂的大神解答一下，谢谢。

**Comment by Honee-W** [comment]
redis已设置远程访问（注释bind，protect mode设为no）

**Comment by jhao104** [comment]
先telnet确认端口是通的吧

**Comment by Honee-W** [comment]
![image](https://user-images.githubusercontent.com/76424822/158315468-ae1f5220-587b-47f2-8a14-447118ffbd9b.png)
![image](https://user-images.githubusercontent.com/76424822/158315794-680a8e9b-8e31-404a-8e8a-207ebabcce15.png)
![image](https://user-images.githubusercontent.com/76424822/158315958-c14805e8-8189-4063-9ce3-d600badf3a49.png)


我使用的命令是docker run --env DB_CONN=redis://:密码@127.0.0.1:6379/0 -p 5010:5010 jhao104/proxy_pool:2.4.0。
问题没有解决，麻烦大佬有空的话再指导一下。

**Comment by Honee-W** [comment]
下载源码后问题解决

**Comment by yzcheung** [comment]
wsl通过docker inspect redis |grep -i add获取实际IPAdress可以解决
