### ISSUE TITLE
连接redis数据库出错了

### ISSUE THREAD

**Issue by Scrooge2** [jhao104/proxy_pool#657]
![截屏2022-04-26 上午10 40 49](https://user-images.githubusercontent.com/40877623/165215571-15bf660e-eb56-4dac-bf96-8aa6e44fdc1b.png)

# 问题

docker和redis都在同一服务器上面项目docker部署的，redis宝塔安装的。我试过了使用127.0.0.1和0.0.0.0都出现各种报错。这里请教下连接redis的方法！！谢谢

**Comment by jhao104** [comment]
你首先要知道在Docker容器里面的127.0.0.1 并不是你宿主机上的127.0.0.1。 你翻翻历史issue，你不是第一个

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/issues/649
https://github.com/jhao104/proxy_pool/issues/600
