### ISSUE TITLE
日志相关问题

### ISSUE THREAD

**Issue by Hao1617** [jhao104/proxy_pool#689]
问一下，我的日志并没有每隔一天生成一个文件。 这个是正常的吗，好像是隔了5天一个文件

```
# 设置日志回滚, 保存在log目录, 一天保存一个文件, 保留15天
file_handler = TimedRotatingFileHandler(filename=file_name, when='D', interval=1, backupCount=15)
```

![image](https://user-images.githubusercontent.com/56282383/184266812-0878fa34-1954-48dd-a92f-3dc86f23e6e2.png)

**Comment by jhao104** [comment]
是的，不会自动rollback。
因为现在的运行方式触发不了条件。
TimedRotatingFileHandler的rollback逻辑是这样的:
```python
    def shouldRollover(self, record):
        """
        Determine if rollover should occur.

        record is not used, as we are just comparing times, but it is needed so
        the method signatures are the same
        """
        t = int(time.time())
        if t >= self.rolloverAt:
            return 1
        return 0
```
`rolloverAt` 是启动的时候根据参数`when`和`interval`算出来的。
而checker和fetcher是每隔几分钟去创建一个新的。这个rolloverAt永远都达不到。除非线程运行超过一天(那是不可能的，一次抓取就几分钟)
