### ISSUE TITLE
用付费代理，有username:password要求，get不到proxy

### ISSUE THREAD

**Issue by aldreamlau** [jhao104/proxy_pool#725]
我的付费代理要求格式这样
![image](https://user-images.githubusercontent.com/5761624/223614482-dfd0e6af-c67d-4ef7-bfb3-5e8cee96742c.png)

我在proxyFetcher.py这样添加
![image](https://user-images.githubusercontent.com/5761624/223614684-b9e05820-86d4-4882-86a3-c4f252244845.png)
setting  这样加
![image](https://user-images.githubusercontent.com/5761624/223614781-7f03b041-2158-43ea-b2a3-41367a494001.png)
运行proxyPool.py schedule，结果这样
![65d4abaed65e723b28abdfe879afb96](https://user-images.githubusercontent.com/5761624/223614907-264eee32-aa9f-478b-9af4-2cff3016233d.png)
rawproxycheck 没看到问题，
useproxycheck 没看到我的代理ip

打开 http://127.0.0.1:5010/get?type=https
没有ip

谢谢

**Comment by jhao104** [comment]
proxyCheck 日志有没有success的

**Comment by aldreamlau** [comment]
一直循环输出以下
![image](https://user-images.githubusercontent.com/5761624/223659972-1dc12e9c-9fe2-4ecf-b824-5561b2a67adc.png)
![image](https://user-images.githubusercontent.com/5761624/223660087-2031d869-7c38-447f-838a-5c1bd25bc234.png)

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/a9760218630472b6740dbbc64b812bc0305f8fee/helper/validator.py#L51-L55

这里有个代理格式的检查，目前没有加需要用户名密码的情况。

按你这种做法 把用户名密码储进去的话，就改这个方法，让他返回True。

另一个做法是  只存ip和端口，在爬虫使用时再加上用户验证信息

**Comment by aldreamlau** [comment]
如果只存ip和端口，check的时候应该也是过不了的吧，因为没有用户密码验证

跳过格式检查的方式可以了，谢谢
