### ISSUE TITLE
requirements.txt中lxml的问题

### ISSUE THREAD

**Issue by Applenice** [jhao104/proxy_pool#73]
您好，我在使用过程中发现在install requirements.txt的时候，在lxml安装阶段报错，看了一下txt文档，lxml是3.7.1的，之后我单独pip了lxml，目前是4.0.0的，安装可以成功。是否可以提交requirements.txt修改？

**Comment by jhao104** [comment]
@Applenice  如果是因为3.7.1版本过低而不能满足功能需求的情况可以升级。 你这个是你安装这个版本出问题，不属于bug吧 :disappointed_relieved:

**Comment by Applenice** [comment]
嘿嘿~不是BUG，不是，我就是跑这跟您说一下我遇见的这个问题来着。非常感谢，嘿嘿，有不懂的还得向您请教（认真脸）。

**Comment by Paulswith** [comment]
同样遇到了这个问题， 环境是python3.7.1 macOS10.14.3，尝试修改requirements可以解决。
![image](https://user-images.githubusercontent.com/24262233/52984386-2b39f480-342a-11e9-98aa-4275311ed2d1.png)
