### ISSUE TITLE
无法启动采集

### ISSUE THREAD

**Issue by tonnychina** [jhao104/proxy_pool#8]
启动采集出现错误：提示 TypeError:__init__() got an unexpected keyword argument minute

**Comment by jhao104** [comment]
你把[ProxyRefreshSchedule.py(https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyRefreshSchedule.py)中`sched.add_job(main, 'interval', minute=20)`的minute改成minutes

**Comment by tonnychina** [comment]
这个问题好了，不过，还有一个问题出现InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised，我直接把ProxyRefreshSchedule.py 里面的 "https": "https://{proxy}".format(proxy=raw_proxy)}这样行给去掉了，
