### ISSUE TITLE
被guobanjia封了

### ISSUE THREAD

**Issue by BadBoyBack** [jhao104/proxy_pool#83]
HTTPConnectionPool(host='www.goubanjia.com', port=80): Max retries exceeded with url: /free/gngn/index1.shtml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015BCF616D30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

增加延时？或者用代理去爬代理？

**Comment by jhao104** [comment]
@BadBoyBack 默认是10分钟抓一次呀，每次就访问了几页而已，应该不会被封掉吧？是不是你的ip在另外程序中访问它，一般网站封IP不会有这么严

**Comment by 1634475170** [comment]
不是被封 是他们网站的服务器偶尔会蹦掉  。

**Comment by renjhchn** [comment]
也碰到这个问题，可能是我一直在爬，也被data5u封了，能出一版用自己5010加代理来爬取的版本吗？
