### ISSUE TITLE
redis默认存放在db0，如何修改为db1或者其他?

### ISSUE THREAD

**Issue by nemochin** [jhao104/proxy_pool#86]
如题

**Comment by jhao104** [comment]
@nemochin 去改redis的DB模块就行.
https://github.com/jhao104/proxy_pool/blob/12cb7205b7518ea8a40447bdeb212f21c5f61397/DB/RedisClient.py#L34

**Comment by jhao104** [comment]
DB_CONN = 'redis://:pwd@127.0.0.1:8888/0'
