### ISSUE TITLE
AttributeError: 'RedisClient' object has no attribute 'exists'

### ISSUE THREAD

**Issue by xbc922** [jhao104/proxy_pool#87]
centos 7 py 3.5.4 用redis 报这个错

**Comment by jhao104** [comment]
@FunnyWuLoveLife  Config.ini 里面DB_type配置成SSDB。 

redis和ssdb数据库都用SSDB的驱动，只改数据库配置就行

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
