### ISSUE TITLE
管理员帮忙再加俩个代理

### ISSUE THREAD

**Issue by TXIuTnVsbA** [jhao104/proxy_pool#89]
url1: http://www.ip3366.net
url2: http://www.kuaidaili.com
我不知道怎么参加修改 - -所以自能= =来这里了= =而且我因为数据库的问题没有下载使用
所以只能贴代码了
https://github.com/TXIuTnVsbA/Test/blob/master/ip3366.py
https://github.com/TXIuTnVsbA/Test/blob/master/kuaidaili.py
= =

**Comment by TXIuTnVsbA** [comment]
还有就是= =
发现一个问题,大佬你的函数validUsefulProxy中只利用r.status_code来检测代理是否可用好像是不行的,
有些代理它会回复代码200,但是内容是代理ip的本地内容了
= =然后拿起来用的时候
- -就发现
= =请求全部都被拒绝了

所以，希望在去除利用r.status_code来检测代理的方法改为匹配内容的方法
还有就是检测ip好像不能只用一个地址去检测= =万一代理ip把这个域名给屏蔽了呢?
最后就是,希望增加对于https检测的功能

**Comment by jhao104** [comment]
@TXIuTnVsbA  代理是分普通和匿名的。code等于200说明请求成功，代理可用。普通代理的话对方服务器可能会检测到你真是IP。你想要的那种应该是高匿。
这个后面我增加个配置。支持匿名检测

**Comment by TXIuTnVsbA** [comment]
@bobobo80 我的意思是说，有些代理容许代理请求，但是回复的内容统一是某网页，如果只是判断code的话，容易把这些ip列入可用的列表里

还有就是想再增加几个测试ip的地址，比如ip.cn
ip138.com这些

我修改了代码了，但是不知道合适不，所以就在这里贴代码地址了
https://github.com/TXIuTnVsbA/proxy_pool/blob/patch-1/Util/utilFunction.py

**Comment by jhao104** [comment]
![image](https://user-images.githubusercontent.com/15058920/33254595-6780699a-d384-11e7-85e2-f175928cc094.png)
直接修改原来的方法就行，返回的json会带上你访问的IP

**Comment by TXIuTnVsbA** [comment]
@jhao104 = =再增加几个检测网站还是ok的万一代理ip把那个拉进黑名单呢

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
