### ISSUE TITLE
爬取过程中API请求会阻塞

### ISSUE THREAD

**Issue by andylee1890** [jhao104/proxy_pool#91]
又加了十来个IP网站，换成了使用代理IP去爬，所以整个爬取过程会比较慢，把任务时间也调成了2小时，但是现在遇到的问题是，在爬取过程中API请求会阻塞，迟迟不响应结果，不太会写python，调试这个问题有点困难，怀疑是redis访问阻塞，我也在看，能否帮忙看看解决问题的思路

**Comment by andylee1890** [comment]
感觉这个API服务很不稳定, 后台爬虫和IP校验还是正常, 但是API接口死活就是调用阻塞

**Comment by andylee1890** [comment]
![image](https://user-images.githubusercontent.com/12568851/33592747-66b2c78a-d9c7-11e7-976b-9d0b6d635e7b.png)
![image](https://user-images.githubusercontent.com/12568851/33592761-732bc494-d9c7-11e7-9ebd-6860621b168e.png)
![image](https://user-images.githubusercontent.com/12568851/33592784-86b782dc-d9c7-11e7-94a3-381a50592c36.png)
分开启动,感觉好了不少

**Comment by jhao104** [comment]
@andylee1890 对的，最好将api服务单独启动，而且这种单进程的方式性能比较低，最好用gunicorn部署起来，具体的你网上搜 gunicorn+flask 教程有很多

**Comment by andylee1890** [comment]
WARNING:requests.packages.urllib3.connectionpool:Failed to parse headers (url=http://218.4.101.130:83/http://httpbin.org/ip): [MissingHeaderBodySeparatorDefect()], unparsed data: '<html>\r\n\r\n'
Traceback (most recent call last):
  File "/usr/python3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 404, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/python3/lib/python3.6/site-packages/requests/packages/urllib3/util/response.py", line 59, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
requests.packages.urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '<html>\r\n\r\n'
@jhao104 现在这个服务总是报这个警告, 出现这个的时候,API接口就坏掉了

**Comment by jhao104** [comment]
@andylee1890 你看看你抓到的代理是不是有很多这种 `'\r\n\r\n'`

**Comment by andylee1890** [comment]
可能有的, 有很多网站都需要正则解析,我拿到之后都去空格了.

`@staticmethod
    def freeProxyNineteen():
        """

        """
        url = "http://www.iphai.com/"
        try:
            tree = getHtmlTree(url)
            proxy_list = tree.xpath('/html/body/div/div/table/tr')
            for proxy in proxy_list:
                try:
                    #yield ':'.join(proxy.xpath('./td/text()')[0:2])
                    yield (proxy.xpath('./td/text()')[0]).strip()+':'+(proxy.xpath('./td/text()')[1]).strip()
                except Exception as e:
                    pass
        except Exception as e:
            pass`

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
