### ISSUE TITLE
proxy速度很滿

### ISSUE THREAD

**Issue by goofi0211** [jhao104/proxy_pool#92]
為什麼我用這些proxy速度都特別慢，一個網頁要等半分鐘這是正常的媽？還是跟這是外國proxy有關西呢，我還是新手有很多愚蠢問題請見諒

**Comment by jhao104** [comment]
@goofi0211 使用代理訪問網頁的速度和代理質量有關，質量好就比較快。當然如果你用國內代理訪問國外網站可能非常慢甚至不能用

**Comment by goofi0211** [comment]
謝謝你回答我，那如果說我用國外的proxy是不是就會快很多呢？
因為我要訪問的是這個網站
http://jirs.judicial.gov.tw/FJUD/index_1.htm
如果是要訪問台灣的網站是不是用這些代理都會有這樣的情形


2017-12-08 17:03 GMT+08:00 J_hao104 <notifications@github.com>:

**Comment by jhao104** [comment]
@goofi0211 應該是的，這個網站國內被墻了，一般的代理上不去的，你的自己去找些國外的代理IP源

**Comment by goofi0211** [comment]
我後來發現用request速度都蠻快的，但是用到selenium就會出錯
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_argument('--proxy-server={0}'.format(proxy))
driver =
webdriver.Chrome(executable_path=r'/Users/terry/chromedriver',chrome_options
= chromeOptions)
driver.get("http://icanhazip.com")
這是我的代碼

潘文傑 <gcobs2336588@gmail.com> 於 2017年12月8日 下午5:10 寫道：

**Comment by jhao104** [comment]
@goofi0211 
```
PROXY = "23.23.23.23:3128" # IP:PORT or HOST:PORT

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--proxy-server=http://%s' % PROXY)
```

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by goofi0211** [comment]
這是什麼啊，顯示404找不到網頁


2018-03-12 19:27 GMT+08:00 luaaaa <notifications@github.com>:
