### ISSUE TITLE
api访问http://127.0.0.1:5010 无法打开

### ISSUE THREAD

**Issue by pybegainer** [jhao104/proxy_pool#93]
求助怎么解决。另外运行时raise TypeError: port must be an integer

**Comment by jhao104** [comment]
@pybegainer 那就是你配置文件写错了，没有启动成功。端口一定要配置数字

**Comment by pybegainer** [comment]
ip = 127.0.0.1
port = 5010
你说的是这个吗？我就是这么写的啊

**Comment by jhao104** [comment]
对的，如果你没有改过 `Api/ProxyApi.py`的话，最好给一下完整点的错误信息， 可能是服务端口，也可能是代理的端口

**Comment by hymzhek** [comment]
少了个括号 https://github.com/jhao104/proxy_pool/pull/95

**Comment by jhao104** [comment]
@hymzhek  ok thx

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
