### ISSUE TITLE
该程序重启会从上一次停止的地方继续吗？

### ISSUE THREAD

**Issue by yangtao4389** [jhao104/proxy_pool#99]
另外，还有个问题：
配置中写到：
freeProxyFirst  = 0  # 如果要取消某个方法，将其删除或赋为0即可
这个是可以实现吗？我分析得出的是不能诶

**Comment by jhao104** [comment]
@yangtao4389  
   第一个问题，这种场景不需要重启的时候继续之前的任务吧。首先，抓到的代理放在消息队列的，重启不会丢失，正在抓的代理，重启会再抓一次。

  第二个问题: 关于代理抓取方式的调用，在这里:
https://github.com/jhao104/proxy_pool/blob/70ef91f85cebadd2638a7938de811b61c0884401/Manager/ProxyManager.py#L42

要取消将其注释或删掉就行，若果要实现赋为0的效果，自己加条判断即可

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
